PreviewView Class Reference
Public Slots
void zoomIn ()
void zoomOut ()
Public Member Functions
PreviewView (QTextDocument *document)
void updateLayout ()
Protected Member Functions
virtual void paintEvent (QPaintEvent *e)
virtual void resizeEvent (QResizeEvent *)
virtual void mousePressEvent (QMouseEvent *e)
virtual void mouseMoveEvent (QMouseEvent *e)
virtual void mouseReleaseEvent (QMouseEvent *e)
Private Member Functions
void paintPage (QPainter *painter, int page)
Private Attributes
QTextDocument * doc
qreal scale
int interPageSpacing
QPoint mousePressPos
QPoint scrollBarValuesOnMousePress
Detailed Description
Definition at line 58 of file printpreview.cpp.
Constructor & Destructor Documentation
PreviewView::PreviewView (QTextDocument * document)
Definition at line 86 of file printpreview.cpp.
References doc, interPageSpacing, and scale.
Member Function Documentation
void PreviewView::updateLayout () [inline]
Definition at line 64 of file printpreview.cpp.
References resizeEvent().
Referenced by PrintPreview::pageSetup().
void PreviewView::zoomIn () [slot]
Definition at line 98 of file printpreview.cpp.
References resizeEvent(), and scale.
void PreviewView::zoomOut () [slot]
Definition at line 105 of file printpreview.cpp.
References resizeEvent(), and scale.
void PreviewView::paintEvent (QPaintEvent * e) [protected, virtual]
Definition at line 112 of file printpreview.cpp.
References doc, interPageSpacing, paintPage(), and scale.
void PreviewView::resizeEvent (QResizeEvent *) [protected, virtual]
Definition at line 162 of file printpreview.cpp.
References doc, interPageSpacing, and scale.
Referenced by updateLayout(), zoomIn(), and zoomOut().
void PreviewView::mousePressEvent (QMouseEvent * e) [protected, virtual]
Definition at line 178 of file printpreview.cpp.
References mousePressPos, and scrollBarValuesOnMousePress.
void PreviewView::mouseMoveEvent (QMouseEvent * e) [protected, virtual]
Definition at line 186 of file printpreview.cpp.
References mousePressPos, and scrollBarValuesOnMousePress.
void PreviewView::mouseReleaseEvent (QMouseEvent * e) [protected, virtual]
Definition at line 200 of file printpreview.cpp.
References mousePressPos.
void PreviewView::paintPage (QPainter * painter, int page) [private]
Definition at line 131 of file printpreview.cpp.
References doc.
Referenced by paintEvent().
Member Data Documentation
QTextDocument* PreviewView::doc [private]
Definition at line 79 of file printpreview.cpp.
Referenced by paintEvent(), paintPage(), PreviewView(), and resizeEvent().
qreal PreviewView::scale [private]
Definition at line 80 of file printpreview.cpp.
Referenced by paintEvent(), PreviewView(), resizeEvent(), zoomIn(), and zoomOut().
int PreviewView::interPageSpacing [private]
Definition at line 81 of file printpreview.cpp.
Referenced by paintEvent(), PreviewView(), and resizeEvent().
QPoint PreviewView::mousePressPos [private]
Definition at line 82 of file printpreview.cpp.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
QPoint PreviewView::scrollBarValuesOnMousePress [private]
Definition at line 83 of file printpreview.cpp.
Referenced by mouseMoveEvent(), and mousePressEvent().
The documentation for this class was generated from the following file:
printpreview.cpp