recordtablemodel Class Reference
#include <recordtablemodel.h>
Public Member Functions
recordtablemodel (QObject *pobj=0)
~recordtablemodel ()
QVariant data (const QModelIndex &index, int nRole) const
bool setData (const QModelIndex &index, const QVariant &value, int nRole)
int rowCount (const QModelIndex &parent=QModelIndex()) const
QAbstractListModel * getmodel (void)
void set_tabledata (recordtabledata *rtdata)
recordtabledata * get_tabledata (void)
void update (void)
Private Attributes
recordtabledata * table
Detailed Description
Definition at line 13 of file recordtablemodel.h.
Constructor & Destructor Documentation
recordtablemodel::recordtablemodel (QObject * pobj = 0)
Definition at line 15 of file recordtablemodel.cpp.
References table.
recordtablemodel::~recordtablemodel ()
Definition at line 26 of file recordtablemodel.cpp.
Member Function Documentation
QVariant recordtablemodel::data (const QModelIndex & index, int nRole) const
Definition at line 34 of file recordtablemodel.cpp.
References recordtabledata::get_field(), and table.
bool recordtablemodel::setData (const QModelIndex & index, const QVariant & value, int nRole)
Definition at line 49 of file recordtablemodel.cpp.
References recordtabledata::set_field(), and table.
int recordtablemodel::rowCount (const QModelIndex & parent = QModelIndex()) const
Definition at line 75 of file recordtablemodel.cpp.
References recordtabledata::size(), and table.
Referenced by recordtablescreen::set_tabledata().
QAbstractListModel * recordtablemodel::getmodel (void)
Definition at line 82 of file recordtablemodel.cpp.
void recordtablemodel::set_tabledata (recordtabledata * rtdata)
Definition at line 88 of file recordtablemodel.cpp.
References table.
Referenced by recordtablescreen::set_tabledata().
recordtabledata * recordtablemodel::get_tabledata (void)
Definition at line 96 of file recordtablemodel.cpp.
References table.
Referenced by recordtablescreen::add_new(), recordtablescreen::copy(), recordtablescreen::delete_records(), recordtablescreen::edit_field(), recordtablescreen::edit_field_context(), recordtablescreen::movedn(), recordtablescreen::moveup(), and recordtablescreen::select().
void recordtablemodel::update (void)
Definition at line 102 of file recordtablemodel.cpp.
Referenced by recordtablescreen::add_new(), and recordtablescreen::delete_records().
Member Data Documentation
recordtabledata* recordtablemodel::table [private]
Definition at line 46 of file recordtablemodel.h.
Referenced by data(), get_tabledata(), recordtablemodel(), rowCount(), set_tabledata(), and setData().
The documentation for this class was generated from the following files:
recordtablemodel.h
recordtablemodel.cpp