editrecord Class Reference
#include <editrecord.h>
Public Member Functions
editrecord (QWidget *parent=0, Qt::WFlags f=0)
~editrecord ()
QString get_field (QString name)
void set_field (QString name, QString value)
Private Slots
void ok_click (void)
Private Member Functions
void setup_ui (void)
void setup_signals (void)
void assembly (void)
Private Attributes
infofieldenter * infofield
QDialogButtonBox * buttonbox
Detailed Description
Definition at line 15 of file editrecord.h.
Constructor & Destructor Documentation
editrecord::editrecord (QWidget * parent = 0, Qt::WFlags f = 0)
Definition at line 12 of file editrecord.cpp.
References assembly(), setup_signals(), and setup_ui().
editrecord::~editrecord ()
Definition at line 19 of file editrecord.cpp.
Member Function Documentation
QString editrecord::get_field (QString name)
Definition at line 91 of file editrecord.cpp.
References infofieldenter::check_field_name(), critical_error(), infofieldenter::get_field(), and infofield.
Referenced by recordtablescreen::edit_field_context().
void editrecord::set_field (QString name, QString value)
Definition at line 102 of file editrecord.cpp.
References infofieldenter::check_field_name(), critical_error(), infofield, and infofieldenter::set_field().
Referenced by recordtablescreen::edit_field_context().
void editrecord::ok_click (void) [private, slot]
Definition at line 69 of file editrecord.cpp.
References infofieldenter::get_field(), and infofield.
Referenced by setup_signals().
void editrecord::setup_ui (void) [private]
Definition at line 25 of file editrecord.cpp.
References buttonbox, and infofield.
Referenced by editrecord().
void editrecord::setup_signals (void) [private]
Definition at line 36 of file editrecord.cpp.
References buttonbox, and ok_click().
Referenced by editrecord().
void editrecord::assembly (void) [private]
Definition at line 42 of file editrecord.cpp.
References buttonbox, infofield, and infofieldenter::set_focus_to_start().
Referenced by editrecord().
Member Data Documentation
infofieldenter* editrecord::infofield [private]
Definition at line 33 of file editrecord.h.
Referenced by assembly(), get_field(), ok_click(), set_field(), and setup_ui().
QDialogButtonBox* editrecord::buttonbox [private]
Definition at line 35 of file editrecord.h.
Referenced by assembly(), setup_signals(), and setup_ui().
The documentation for this class was generated from the following files:
editrecord.h
editrecord.cpp