addnewrecord Class Reference
#include <addnewrecord.h>
Public Member Functions
addnewrecord (QWidget *parent=0, Qt::WFlags f=0)
~addnewrecord ()
QString get_field (QString name)
Private Slots
void ok_click (void)
Private Member Functions
void setup_ui (void)
void setup_signals (void)
void assembly (void)
Private Attributes
infofieldenter * infofield
editor * recordtext_editor
QDialogButtonBox * buttonbox
Detailed Description
Definition at line 16 of file addnewrecord.h.
Constructor & Destructor Documentation
addnewrecord::addnewrecord (QWidget * parent = 0, Qt::WFlags f = 0)
Definition at line 13 of file addnewrecord.cpp.
References assembly(), setup_signals(), and setup_ui().
addnewrecord::~addnewrecord ()
Definition at line 20 of file addnewrecord.cpp.
Member Function Documentation
QString addnewrecord::get_field (QString name)
Definition at line 102 of file addnewrecord.cpp.
References infofieldenter::get_field(), editor::get_textarea(), infofield, and recordtext_editor.
Referenced by recordtablescreen::add_new_record(), and ok_click().
void addnewrecord::ok_click (void) [private, slot]
Definition at line 71 of file addnewrecord.cpp.
References get_field(), infofieldenter::get_field(), and infofield.
Referenced by setup_signals().
void addnewrecord::setup_ui (void) [private]
Definition at line 26 of file addnewrecord.cpp.
References buttonbox, ENABLE_ASSEMBLY, infofield, and recordtext_editor.
Referenced by addnewrecord().
void addnewrecord::setup_signals (void) [private]
Definition at line 42 of file addnewrecord.cpp.
References buttonbox, and ok_click().
Referenced by addnewrecord().
void addnewrecord::assembly (void) [private]
Definition at line 48 of file addnewrecord.cpp.
References buttonbox, infofield, recordtext_editor, and infofieldenter::set_focus_to_start().
Referenced by addnewrecord().
Member Data Documentation
infofieldenter* addnewrecord::infofield [private]
Definition at line 33 of file addnewrecord.h.
Referenced by assembly(), get_field(), ok_click(), and setup_ui().
editor* addnewrecord::recordtext_editor [private]
Definition at line 36 of file addnewrecord.h.
Referenced by assembly(), get_field(), and setup_ui().
QDialogButtonBox* addnewrecord::buttonbox [private]
Definition at line 38 of file addnewrecord.h.
Referenced by assembly(), setup_signals(), and setup_ui().
The documentation for this class was generated from the following files:
addnewrecord.h
addnewrecord.cpp