TreeItem Class Reference
#include <treeitem.h>
Public Member Functions
TreeItem (const QMap< QString, QString > &data, TreeItem *parent=0)
~TreeItem ()
TreeItem * child (int number)
int childCount () const
int fieldCount () const
QVariant data (QString name)
void setData (QString n, QString v)
bool insertChildren (int position, int count, int columns)
bool addChildren (void)
TreeItem * parent ()
bool removeChildren (int position, int count)
int childNumber () const
bool move_up (void)
bool move_dn (void)
QStringList get_path (void)
QStringList get_path_as_name (void)
QList< QStringList > get_all_children_path (void)
void recordtable_init (QDomElement dommodel)
int recordtable_getrowcount (void)
void recordtable_clear (void)
QDomDocument recordtable_export_data_to_dom (void)
recordtabledata * recordtable_gettabledata (void)
Private Member Functions
bool removeChildrenLink (int position, int count)
QList< QStringList > get_all_children_path_recurse (TreeItem *item, int mode)
QStringList get_path_as_field (QString field)
Private Attributes
QList< TreeItem * > childItems
TreeItem * parentItem
QMap< QString, QString > fieldtable
recordtabledata rtable
Detailed Description
Definition at line 13 of file treeitem.h.
Constructor & Destructor Documentation
TreeItem::TreeItem (const QMap< QString, QString > & data, TreeItem * parent = 0)
Definition at line 13 of file treeitem.cpp.
References fieldtable, parent(), and parentItem.
Referenced by addChildren(), and insertChildren().
TreeItem::~TreeItem ()
Definition at line 20 of file treeitem.cpp.
References childItems, and recordtable_clear().
Member Function Documentation
TreeItem * TreeItem::child (int number)
Definition at line 34 of file treeitem.cpp.
References childItems.
Referenced by findscreen::find_recurse(), get_all_children_path_recurse(), TreeModel::getItem(), TreeModel::index(), knowtreemodel::indexChildren(), knowtreemodel::parsenodeelement(), and knowtreemodel::parsetreetodom().
int TreeItem::childCount () const
Definition at line 41 of file treeitem.cpp.
References childItems.
Referenced by findscreen::find_recurse(), get_all_children_path_recurse(), TreeModel::getItem(), knowtreemodel::indexChildren(), treescreen::ins_branch(), treescreen::ins_subbranch(), move_dn(), knowtreemodel::parsenodeelement(), knowtreemodel::parsetreetodom(), and TreeModel::rowCount().
int TreeItem::fieldCount () const
Definition at line 58 of file treeitem.cpp.
References fieldtable.
QVariant TreeItem::data (QString name)
Definition at line 65 of file treeitem.cpp.
References critical_error(), fieldtable, and recordtable_getrowcount().
Referenced by addChildren(), TreeModel::data(), treescreen::del_branch(), treescreen::edit_branch(), findscreen::find_recurse(), get_path_as_field(), insertChildren(), knowtreemodel::parsetreetodom(), and mainwindow::set_tree_position().
void TreeItem::setData (QString n, QString v)
Definition at line 101 of file treeitem.cpp.
References fieldtable.
Referenced by treescreen::edit_branch(), TreeModel::setData(), and TreeModel::setHeaderData().
bool TreeItem::insertChildren (int position, int count, int columns)
Definition at line 128 of file treeitem.cpp.
References childItems, data(), and TreeItem().
Referenced by TreeModel::insertRows(), and knowtreemodel::parsenodeelement().
bool TreeItem::addChildren (void)
Definition at line 145 of file treeitem.cpp.
References childItems, data(), and TreeItem().
TreeItem * TreeItem::parent ()
Definition at line 118 of file treeitem.cpp.
References parentItem.
Referenced by knowtreemodel::add_new_sibling_branch(), get_path_as_field(), treescreen::ins_branch(), TreeModel::parent(), and TreeItem().
bool TreeItem::removeChildren (int position, int count)
Definition at line 157 of file treeitem.cpp.
References childItems.
Referenced by TreeModel::removeRows().
int TreeItem::childNumber () const
Definition at line 49 of file treeitem.cpp.
References childItems, and parentItem.
Referenced by knowtreemodel::get_item_index(), move_dn(), move_up(), and TreeModel::parent().
bool TreeItem::move_up (void)
Definition at line 182 of file treeitem.cpp.
References childItems, childNumber(), and parentItem.
Referenced by knowtreemodel::move_updn_branch().
bool TreeItem::move_dn (void)
Definition at line 197 of file treeitem.cpp.
References childCount(), childItems, childNumber(), and parentItem.
Referenced by knowtreemodel::move_updn_branch().
QStringList TreeItem::get_path (void)
Definition at line 213 of file treeitem.cpp.
References get_path_as_field().
Referenced by findscreen::find_recurse(), get_all_children_path_recurse(), and mainwindow::save_tree_position().
QStringList TreeItem::get_path_as_name (void)
Definition at line 219 of file treeitem.cpp.
References get_path_as_field().
QList< QStringList > TreeItem::get_all_children_path (void)
Definition at line 248 of file treeitem.cpp.
References get_all_children_path_recurse().
void TreeItem::recordtable_init (QDomElement dommodel)
Definition at line 285 of file treeitem.cpp.
References recordtabledata::init(), and rtable.
Referenced by knowtreemodel::parsenodeelement().
int TreeItem::recordtable_getrowcount (void)
Definition at line 291 of file treeitem.cpp.
References rtable, and recordtabledata::size().
Referenced by TreeModel::data(), data(), findscreen::find_recurse(), and knowtreemodel::parsetreetodom().
void TreeItem::recordtable_clear (void)
Definition at line 303 of file treeitem.cpp.
References recordtabledata::clear(), and rtable.
Referenced by ~TreeItem().
QDomDocument TreeItem::recordtable_export_data_to_dom (void)
Definition at line 297 of file treeitem.cpp.
References recordtabledata::export_data_to_dom(), and rtable.
Referenced by knowtreemodel::parsetreetodom().
recordtabledata * TreeItem::recordtable_gettabledata (void)
Definition at line 308 of file treeitem.cpp.
References rtable.
Referenced by findscreen::find_recurse(), and treescreen::on_knowtree_clicked().
bool TreeItem::removeChildrenLink (int position, int count) [private]
Definition at line 169 of file treeitem.cpp.
References childItems.
QList< QStringList > TreeItem::get_all_children_path_recurse (TreeItem * item, int mode) [private]
Definition at line 262 of file treeitem.cpp.
References child(), childCount(), and get_path().
Referenced by get_all_children_path().
QStringList TreeItem::get_path_as_field (QString field) [private]
Definition at line 225 of file treeitem.cpp.
References data(), and parent().
Referenced by get_path(), and get_path_as_name().
Member Data Documentation
QList<TreeItem*> TreeItem::childItems [private]
Definition at line 87 of file treeitem.h.
Referenced by addChildren(), child(), childCount(), childNumber(), insertChildren(), move_dn(), move_up(), removeChildren(), removeChildrenLink(), and ~TreeItem().
TreeItem* TreeItem::parentItem [private]
Definition at line 88 of file treeitem.h.
Referenced by childNumber(), move_dn(), move_up(), parent(), and TreeItem().
QMap<QString, QString> TreeItem::fieldtable [private]
Definition at line 91 of file treeitem.h.
Referenced by data(), fieldCount(), setData(), and TreeItem().
recordtabledata TreeItem::rtable [private]
Definition at line 94 of file treeitem.h.
Referenced by recordtable_clear(), recordtable_export_data_to_dom(), recordtable_getrowcount(), recordtable_gettabledata(), and recordtable_init().
The documentation for this class was generated from the following files:
treeitem.h
treeitem.cpp