infofieldenter Class Reference
#include <infofieldenter.h>
Public Slots
void expand_info_click (void)
Public Member Functions
infofieldenter (QWidget *parent=0)
~infofieldenter ()
void set_focus_to_start (void)
bool check_field_name (QString name)
QString get_field (QString name)
void set_field (QString name, QString value)
Private Member Functions
void setup_ui (void)
void setup_signals (void)
void assembly (void)
void expand_info_on_display (QString expand)
Private Attributes
QLabel * recordname_label
QLineEdit * recordname
QLabel * recordauthor_label
QLineEdit * recordauthor
QLabel * recordurl_label
QLineEdit * recordurl
QLabel * recordtags_label
QLineEdit * recordtags
QToolButton * expand_info
QGridLayout * infofieldlayout
Detailed Description
Definition at line 15 of file infofieldenter.h.
Constructor & Destructor Documentation
infofieldenter::infofieldenter (QWidget * parent = 0)
Definition at line 10 of file infofieldenter.cpp.
References assembly(), setup_signals(), and setup_ui().
infofieldenter::~infofieldenter ()
Definition at line 17 of file infofieldenter.cpp.
Member Function Documentation
void infofieldenter::set_focus_to_start (void)
Definition at line 153 of file infofieldenter.cpp.
References recordname.
Referenced by editrecord::assembly(), and addnewrecord::assembly().
bool infofieldenter::check_field_name (QString name)
Definition at line 158 of file infofieldenter.cpp.
Referenced by get_field(), editrecord::get_field(), set_field(), and editrecord::set_field().
QString infofieldenter::get_field (QString name)
Definition at line 170 of file infofieldenter.cpp.
References check_field_name(), critical_error(), recordauthor, recordname, recordtags, and recordurl.
Referenced by editrecord::get_field(), addnewrecord::get_field(), editrecord::ok_click(), and addnewrecord::ok_click().
void infofieldenter::set_field (QString name, QString value)
Definition at line 186 of file infofieldenter.cpp.
References check_field_name(), critical_error(), recordauthor, recordname, recordtags, and recordurl.
Referenced by editrecord::set_field().
void infofieldenter::expand_info_click (void) [slot]
Definition at line 129 of file infofieldenter.cpp.
References expand_info, expand_info_on_display(), appconfig::get_addnewrecord_expand_info(), mytetraconfig, and appconfig::set_addnewrecord_expand_info().
Referenced by setup_signals().
void infofieldenter::setup_ui (void) [private]
Definition at line 22 of file infofieldenter.cpp.
References expand_info, appconfig::get_addnewrecord_expand_info(), imin(), mytetraconfig, recordauthor, recordauthor_label, recordname, recordname_label, recordtags, recordtags_label, recordurl, and recordurl_label.
Referenced by infofieldenter().
void infofieldenter::setup_signals (void) [private]
Definition at line 63 of file infofieldenter.cpp.
References expand_info, and expand_info_click().
Referenced by infofieldenter().
void infofieldenter::assembly (void) [private]
Definition at line 70 of file infofieldenter.cpp.
References expand_info, expand_info_on_display(), appconfig::get_addnewrecord_expand_info(), infofieldlayout, mytetraconfig, recordauthor, recordauthor_label, recordname, recordname_label, recordtags, recordtags_label, recordurl, and recordurl_label.
Referenced by infofieldenter().
void infofieldenter::expand_info_on_display (QString expand) [private]
Definition at line 109 of file infofieldenter.cpp.
References recordauthor, recordauthor_label, recordtags, recordtags_label, recordurl, and recordurl_label.
Referenced by assembly(), and expand_info_click().
Member Data Documentation
QLabel* infofieldenter::recordname_label [private]
Definition at line 36 of file infofieldenter.h.
Referenced by assembly(), and setup_ui().
QLineEdit* infofieldenter::recordname [private]
Definition at line 37 of file infofieldenter.h.
Referenced by assembly(), get_field(), set_field(), set_focus_to_start(), and setup_ui().
QLabel* infofieldenter::recordauthor_label [private]
Definition at line 40 of file infofieldenter.h.
Referenced by assembly(), expand_info_on_display(), and setup_ui().
QLineEdit* infofieldenter::recordauthor [private]
Definition at line 41 of file infofieldenter.h.
Referenced by assembly(), expand_info_on_display(), get_field(), set_field(), and setup_ui().
QLabel* infofieldenter::recordurl_label [private]
Definition at line 44 of file infofieldenter.h.
Referenced by assembly(), expand_info_on_display(), and setup_ui().
QLineEdit* infofieldenter::recordurl [private]
Definition at line 45 of file infofieldenter.h.
Referenced by assembly(), expand_info_on_display(), get_field(), set_field(), and setup_ui().
QLabel* infofieldenter::recordtags_label [private]
Definition at line 48 of file infofieldenter.h.
Referenced by assembly(), expand_info_on_display(), and setup_ui().
QLineEdit* infofieldenter::recordtags [private]
Definition at line 49 of file infofieldenter.h.
Referenced by assembly(), expand_info_on_display(), get_field(), set_field(), and setup_ui().
QToolButton* infofieldenter::expand_info [private]
Definition at line 52 of file infofieldenter.h.
Referenced by assembly(), expand_info_click(), setup_signals(), and setup_ui().
QGridLayout* infofieldenter::infofieldlayout [private]
Definition at line 55 of file infofieldenter.h.
Referenced by assembly().
The documentation for this class was generated from the following files:
infofieldenter.h
infofieldenter.cpp