recordtablescreen Class Reference
#include <recordtablescreen.h>
Public Member Functions
recordtablescreen (QWidget *parent=0)
virtual ~recordtablescreen ()
QString get_currentdir (void)
QString get_currentfile (void)
QString get_fullfilename_of_currentitem (void)
void save (void)
void set_tabledata (recordtabledata *)
int get_first_selection_pos (void)
void set_selection_to_pos (int pos)
bool is_selected_set_to_top (void)
bool is_selected_set_to_bottom (void)
Private Slots
void select (const QModelIndex &index)
void tools_update (void)
void on_customContextMenuRequested (const QPoint &pos)
void add_new_toend_context (void)
void add_new_before_context (void)
void add_new_after_context (void)
void edit_field_context (void)
void delete_context (void)
void cut (void)
void copy (void)
void paste (void)
void moveup (void)
void movedn (void)
void findinbase_open (void)
Private Member Functions
void setup_ui (void)
void setup_signals (void)
void setup_actions (void)
void assembly (void)
void disable_all_actions (void)
void add_new_record (int mode)
void add_new (int mode, QString name, QString author, QString url, QString tags, QString text)
void edit_field (int pos, QString name, QString author, QString url, QString tags)
void delete_records (void)
Private Attributes
QToolBar * tools_line
QToolBar * find_line
QListView * recordview
recordtablemodel * recordmodel
QHBoxLayout * recordtable_tools_layout
QVBoxLayout * recordtablescreen_layout
QAction * action_add_new_toend
QAction * action_add_new_before
QAction * action_add_new_after
QAction * action_edit_field
QAction * action_delete
QAction * action_cut
QAction * action_copy
QAction * action_paste
QAction * action_moveup
QAction * action_movedn
QAction * action_findinbase
QString recordview_currentdir
QString recordview_currentfile
Detailed Description
Definition at line 15 of file recordtablescreen.h.
Constructor & Destructor Documentation
recordtablescreen::recordtablescreen (QWidget * parent = 0)
Definition at line 14 of file recordtablescreen.cpp.
References assembly(), recordmodel, recordview, recordview_currentdir, recordview_currentfile, setup_actions(), setup_signals(), and setup_ui().
recordtablescreen::~recordtablescreen () [virtual]
Definition at line 37 of file recordtablescreen.cpp.
Member Function Documentation
QString recordtablescreen::get_currentdir (void)
Definition at line 233 of file recordtablescreen.cpp.
References recordview_currentdir.
Referenced by mainwindow::save_current_record_text().
QString recordtablescreen::get_currentfile (void)
Definition at line 239 of file recordtablescreen.cpp.
References recordview_currentfile.
Referenced by mainwindow::save_current_record_text().
QString recordtablescreen::get_fullfilename_of_currentitem (void)
Definition at line 246 of file recordtablescreen.cpp.
References appconfig::get_tetradir(), mytetraconfig, recordview_currentdir, and recordview_currentfile.
Referenced by mainwindow::save_current_record_text().
void recordtablescreen::save (void)
void recordtablescreen::set_tabledata (recordtabledata *)
Definition at line 197 of file recordtablescreen.cpp.
References recordmodel, recordview, recordview_currentdir, recordview_currentfile, recordtablemodel::rowCount(), and recordtablemodel::set_tabledata().
int recordtablescreen::get_first_selection_pos (void)
Definition at line 817 of file recordtablescreen.cpp.
References recordview.
Referenced by add_new(), is_selected_set_to_bottom(), is_selected_set_to_top(), movedn(), moveup(), and mainwindow::save_recordtable_position().
void recordtablescreen::set_selection_to_pos (int pos)
Definition at line 844 of file recordtablescreen.cpp.
References recordmodel, and recordview.
Referenced by movedn(), moveup(), and mainwindow::set_recordtable_position().
bool recordtablescreen::is_selected_set_to_top (void)
Definition at line 829 of file recordtablescreen.cpp.
References get_first_selection_pos().
Referenced by tools_update().
bool recordtablescreen::is_selected_set_to_bottom (void)
Definition at line 836 of file recordtablescreen.cpp.
References get_first_selection_pos(), and recordview.
Referenced by tools_update().
void recordtablescreen::select (const QModelIndex & index) [private, slot]
Definition at line 254 of file recordtablescreen.cpp.
References critical_error(), recordtabledata::get_field(), recordtablemodel::get_tabledata(), appconfig::get_tetradir(), mytetraconfig, recordmodel, recordview_currentdir, recordview_currentfile, metaeditor::set_author(), metaeditor::set_name(), metaeditor::set_tags(), editor::set_textarea(), and metaeditor::set_url().
Referenced by edit_field_context(), and setup_signals().
void recordtablescreen::tools_update (void) [private, slot]
Definition at line 657 of file recordtablescreen.cpp.
References action_add_new_after, action_add_new_before, action_add_new_toend, action_copy, action_cut, action_delete, action_edit_field, action_movedn, action_moveup, action_paste, disable_all_actions(), is_selected_set_to_bottom(), is_selected_set_to_top(), and recordview.
Referenced by setup_signals().
void recordtablescreen::on_customContextMenuRequested (const QPoint & pos) [private, slot]
Definition at line 747 of file recordtablescreen.cpp.
References action_add_new_after, action_add_new_before, action_add_new_toend, action_copy, action_cut, action_delete, action_edit_field, action_paste, and recordview.
Referenced by setup_signals().
void recordtablescreen::add_new_toend_context (void) [private, slot]
Definition at line 302 of file recordtablescreen.cpp.
References add_new_record(), and ADD_NEW_RECORD_TO_END.
Referenced by setup_actions().
void recordtablescreen::add_new_before_context (void) [private, slot]
Definition at line 311 of file recordtablescreen.cpp.
References add_new_record(), and ADD_NEW_RECORD_BEFORE.
Referenced by setup_actions().
void recordtablescreen::add_new_after_context (void) [private, slot]
Definition at line 320 of file recordtablescreen.cpp.
References add_new_record(), and ADD_NEW_RECORD_AFTER.
Referenced by setup_actions().
void recordtablescreen::edit_field_context (void) [private, slot]
Definition at line 385 of file recordtablescreen.cpp.
References edit_field(), editrecord::get_field(), recordtabledata::get_field(), recordtablemodel::get_tabledata(), recordmodel, recordview, select(), and editrecord::set_field().
Referenced by setup_actions(), and setup_signals().
void recordtablescreen::delete_context (void) [private, slot]
Definition at line 454 of file recordtablescreen.cpp.
References delete_records().
Referenced by setup_actions().
void recordtablescreen::cut (void) [private, slot]
Definition at line 554 of file recordtablescreen.cpp.
References copy(), and delete_records().
Referenced by setup_actions().
void recordtablescreen::copy (void) [private, slot]
Definition at line 561 of file recordtablescreen.cpp.
References clipbrecords::add_record(), recordtabledata::get_record_img(), recordtablemodel::get_tabledata(), clipbrecords::print(), recordmodel, and recordview.
Referenced by cut(), and setup_actions().
void recordtablescreen::paste (void) [private, slot]
Definition at line 597 of file recordtablescreen.cpp.
References add_new(), ADD_NEW_RECORD_TO_END, clipbrecords::get_record(), clipbrecords::get_records_num(), and clipbrecords::print().
Referenced by setup_actions().
void recordtablescreen::moveup (void) [private, slot]
Definition at line 771 of file recordtablescreen.cpp.
References get_first_selection_pos(), recordtablemodel::get_tabledata(), recordtabledata::moveup(), recordmodel, and set_selection_to_pos().
Referenced by setup_actions().
void recordtablescreen::movedn (void) [private, slot]
Definition at line 794 of file recordtablescreen.cpp.
References get_first_selection_pos(), recordtablemodel::get_tabledata(), recordtabledata::movedn(), recordmodel, and set_selection_to_pos().
Referenced by setup_actions().
void recordtablescreen::findinbase_open (void) [private, slot]
Definition at line 855 of file recordtablescreen.cpp.
References findscreen::widget_hide(), and findscreen::widget_show().
Referenced by setup_actions().
void recordtablescreen::setup_ui (void) [private]
Definition at line 114 of file recordtablescreen.cpp.
References action_add_new_toend, action_copy, action_cut, action_delete, action_edit_field, action_findinbase, action_movedn, action_moveup, action_paste, find_line, recordview, and tools_line.
Referenced by recordtablescreen().
void recordtablescreen::setup_signals (void) [private]
Definition at line 138 of file recordtablescreen.cpp.
References edit_field_context(), on_customContextMenuRequested(), recordview, select(), and tools_update().
Referenced by recordtablescreen().
void recordtablescreen::setup_actions (void) [private]
Definition at line 43 of file recordtablescreen.cpp.
References action_add_new_after, action_add_new_before, action_add_new_toend, action_copy, action_cut, action_delete, action_edit_field, action_findinbase, action_movedn, action_moveup, action_paste, add_new_after_context(), add_new_before_context(), add_new_toend_context(), copy(), cut(), delete_context(), disable_all_actions(), edit_field_context(), findinbase_open(), movedn(), moveup(), and paste().
Referenced by recordtablescreen().
void recordtablescreen::assembly (void) [private]
Definition at line 174 of file recordtablescreen.cpp.
References find_line, recordtable_tools_layout, recordtablescreen_layout, recordview, and tools_line.
Referenced by recordtablescreen().
void recordtablescreen::disable_all_actions (void) [private]
Definition at line 640 of file recordtablescreen.cpp.
References action_add_new_after, action_add_new_before, action_add_new_toend, action_copy, action_cut, action_delete, action_edit_field, action_movedn, action_moveup, and action_paste.
Referenced by setup_actions(), and tools_update().
void recordtablescreen::add_new_record (int mode) [private]
Definition at line 329 of file recordtablescreen.cpp.
References add_new(), and addnewrecord::get_field().
Referenced by add_new_after_context(), add_new_before_context(), and add_new_toend_context().
void recordtablescreen::add_new (int mode, QString name, QString author, QString url, QString tags, QString text) [private]
Definition at line 349 of file recordtablescreen.cpp.
References get_first_selection_pos(), recordtablemodel::get_tabledata(), recordtabledata::insert_new_record(), recordmodel, recordview, and recordtablemodel::update().
Referenced by add_new_record(), and paste().
void recordtablescreen::edit_field (int pos, QString name, QString author, QString url, QString tags) [private]
Definition at line 424 of file recordtablescreen.cpp.
References recordtabledata::edit_record(), recordtablemodel::get_tabledata(), recordmodel, metaeditor::set_author(), metaeditor::set_name(), metaeditor::set_tags(), and metaeditor::set_url().
Referenced by edit_field_context().
void recordtablescreen::delete_records (void) [private]
Definition at line 476 of file recordtablescreen.cpp.
References recordtabledata::delete_records(), recordtablemodel::get_tabledata(), recordmodel, recordview, recordtabledata::size(), and recordtablemodel::update().
Referenced by cut(), and delete_context().
Member Data Documentation
QToolBar* recordtablescreen::tools_line [private]
Definition at line 75 of file recordtablescreen.h.
Referenced by assembly(), and setup_ui().
QToolBar* recordtablescreen::find_line [private]
Definition at line 76 of file recordtablescreen.h.
Referenced by assembly(), and setup_ui().
QListView* recordtablescreen::recordview [private]
Definition at line 78 of file recordtablescreen.h.
Referenced by add_new(), assembly(), copy(), delete_records(), edit_field_context(), get_first_selection_pos(), is_selected_set_to_bottom(), on_customContextMenuRequested(), recordtablescreen(), set_selection_to_pos(), set_tabledata(), setup_signals(), setup_ui(), and tools_update().
recordtablemodel* recordtablescreen::recordmodel [private]
Definition at line 79 of file recordtablescreen.h.
Referenced by add_new(), copy(), delete_records(), edit_field(), edit_field_context(), movedn(), moveup(), recordtablescreen(), select(), set_selection_to_pos(), and set_tabledata().
QHBoxLayout* recordtablescreen::recordtable_tools_layout [private]
Definition at line 81 of file recordtablescreen.h.
Referenced by assembly().
QVBoxLayout* recordtablescreen::recordtablescreen_layout [private]
Definition at line 82 of file recordtablescreen.h.
Referenced by assembly().
QAction* recordtablescreen::action_add_new_toend [private]
Definition at line 84 of file recordtablescreen.h.
Referenced by disable_all_actions(), on_customContextMenuRequested(), setup_actions(), setup_ui(), and tools_update().
QAction* recordtablescreen::action_add_new_before [private]
Definition at line 85 of file recordtablescreen.h.
Referenced by disable_all_actions(), on_customContextMenuRequested(), setup_actions(), and tools_update().
QAction* recordtablescreen::action_add_new_after [private]
Definition at line 86 of file recordtablescreen.h.
Referenced by disable_all_actions(), on_customContextMenuRequested(), setup_actions(), and tools_update().
QAction* recordtablescreen::action_edit_field [private]
Definition at line 87 of file recordtablescreen.h.
Referenced by disable_all_actions(), on_customContextMenuRequested(), setup_actions(), setup_ui(), and tools_update().
QAction* recordtablescreen::action_delete [private]
Definition at line 88 of file recordtablescreen.h.
Referenced by disable_all_actions(), on_customContextMenuRequested(), setup_actions(), setup_ui(), and tools_update().
QAction* recordtablescreen::action_cut [private]
Definition at line 89 of file recordtablescreen.h.
Referenced by disable_all_actions(), on_customContextMenuRequested(), setup_actions(), setup_ui(), and tools_update().
QAction* recordtablescreen::action_copy [private]
Definition at line 90 of file recordtablescreen.h.
Referenced by disable_all_actions(), on_customContextMenuRequested(), setup_actions(), setup_ui(), and tools_update().
QAction* recordtablescreen::action_paste [private]
Definition at line 91 of file recordtablescreen.h.
Referenced by disable_all_actions(), on_customContextMenuRequested(), setup_actions(), setup_ui(), and tools_update().
QAction* recordtablescreen::action_moveup [private]
Definition at line 92 of file recordtablescreen.h.
Referenced by disable_all_actions(), setup_actions(), setup_ui(), and tools_update().
QAction* recordtablescreen::action_movedn [private]
Definition at line 93 of file recordtablescreen.h.
Referenced by disable_all_actions(), setup_actions(), setup_ui(), and tools_update().
QAction* recordtablescreen::action_findinbase [private]
Definition at line 94 of file recordtablescreen.h.
Referenced by setup_actions(), and setup_ui().
QString recordtablescreen::recordview_currentdir [private]
Definition at line 101 of file recordtablescreen.h.
Referenced by get_currentdir(), get_fullfilename_of_currentitem(), recordtablescreen(), select(), and set_tabledata().
QString recordtablescreen::recordview_currentfile [private]
Definition at line 102 of file recordtablescreen.h.
Referenced by get_currentfile(), get_fullfilename_of_currentitem(), recordtablescreen(), select(), and set_tabledata().
The documentation for this class was generated from the following files:
recordtablescreen.h
recordtablescreen.cpp