findtablewidget Class Reference
#include <findtablewidget.h>
Public Member Functions
findtablewidget (QWidget *parent=0)
virtual ~findtablewidget (void)
void clear_all (void)
void add_row (QString title, QString branchname, QString tags, QStringList path, int num_in_recordtable)
void update_columns_width (void)
Private Slots
void select_cell (int row, int column)
Private Member Functions
void setup_ui (void)
void setup_signals (void)
void assembly (void)
bool eventFilter (QObject *o, QEvent *e)
Private Attributes
QTableWidget * findtableview
Detailed Description
Definition at line 10 of file findtablewidget.h.
Constructor & Destructor Documentation
findtablewidget::findtablewidget (QWidget * parent = 0)
Definition at line 12 of file findtablewidget.cpp.
References assembly(), clear_all(), setup_signals(), and setup_ui().
findtablewidget::~findtablewidget (void) [virtual]
Definition at line 22 of file findtablewidget.cpp.
Member Function Documentation
void findtablewidget::clear_all (void)
Definition at line 73 of file findtablewidget.cpp.
References findtableview.
Referenced by findscreen::find_start(), and findtablewidget().
void findtablewidget::add_row (QString title, QString branchname, QString tags, QStringList path, int num_in_recordtable)
Definition at line 92 of file findtablewidget.cpp.
References findtableview.
Referenced by findscreen::find_recurse().
void findtablewidget::update_columns_width (void)
Definition at line 65 of file findtablewidget.cpp.
References findtableview.
Referenced by findscreen::find_start().
void findtablewidget::select_cell (int row, int column) [private, slot]
Definition at line 137 of file findtablewidget.cpp.
References findtableview.
Referenced by setup_signals().
void findtablewidget::setup_ui (void) [private]
Definition at line 27 of file findtablewidget.cpp.
References findtableview.
Referenced by findtablewidget().
void findtablewidget::setup_signals (void) [private]
Definition at line 46 of file findtablewidget.cpp.
References findtableview, and select_cell().
Referenced by findtablewidget().
void findtablewidget::assembly (void) [private]
Definition at line 54 of file findtablewidget.cpp.
References findtableview.
Referenced by findtablewidget().
bool findtablewidget::eventFilter (QObject * o, QEvent * e) [private]
Definition at line 123 of file findtablewidget.cpp.
References findtableview.
Member Data Documentation
QTableWidget* findtablewidget::findtableview [private]
Definition at line 26 of file findtablewidget.h.
Referenced by add_row(), assembly(), clear_all(), eventFilter(), select_cell(), setup_signals(), setup_ui(), and update_columns_width().
The documentation for this class was generated from the following files:
findtablewidget.h
findtablewidget.cpp