mainwindow Class Reference
#include <mainwindow.h>
Public Member Functions
mainwindow ()
~mainwindow ()
void save_current_record_text (void)
void restore_geometry (void)
void restore_tree_position (void)
void restore_recordtable_position (void)
void restore_findonbase_visible (void)
void set_tree_position (QStringList path)
void set_recordtable_position (int n)
Public Attributes
treescreen * treeview
recordtablescreen * recordtableview
metaeditor * editorview
findscreen * findscreendisp
QStatusBar * statbar
Protected Member Functions
void closeEvent (QCloseEvent *event)
Private Slots
void fileNew (void)
void fileOpen (void)
bool fileSave (void)
bool fileSaveAs (void)
void filePrint (void)
void filePrintPreview (void)
void filePrintPdf (void)
void icon_activated (QSystemTrayIcon::ActivationReason reason)
void application_exit (void)
Private Member Functions
void setup_ui (void)
void setup_signals (void)
void assembly (void)
void initFileActions (void)
void initRecordTableActions (void)
void setup_icon_actions (void)
void create_tray_icon (void)
void set_icon (void)
void save_geometry (void)
void save_tree_position (void)
void save_recordtable_position (void)
Private Attributes
QAction * tray_restore_action
QAction * tray_maximize_action
QAction * tray_minimize_action
QAction * tray_quit_action
QSystemTrayIcon * tray_icon
QMenu * tray_icon_menu
QSplitter * vspl
QSplitter * hspl
QSplitter * findsplitter
Detailed Description
Definition at line 71 of file mainwindow.h.
Constructor & Destructor Documentation
mainwindow::mainwindow ()
Definition at line 11 of file mainwindow.cpp.
References assembly(), create_tray_icon(), initFileActions(), set_icon(), setup_icon_actions(), setup_signals(), setup_ui(), and tray_icon.
mainwindow::~mainwindow ()
Definition at line 27 of file mainwindow.cpp.
References editorview, recordtableview, save_current_record_text(), save_geometry(), save_recordtable_position(), save_tree_position(), and treeview.
Member Function Documentation
void mainwindow::save_current_record_text (void)
Definition at line 415 of file mainwindow.cpp.
References editorview, recordtablescreen::get_currentdir(), recordtablescreen::get_currentfile(), recordtablescreen::get_fullfilename_of_currentitem(), appconfig::get_lastprefixnum_as_line(), appconfig::get_trashdir(), appconfig::inc_lastprefixnum(), mytetraconfig, recordtableview, and editor::textarea.
Referenced by ~mainwindow().
void mainwindow::restore_geometry (void)
Definition at line 96 of file mainwindow.cpp.
References findsplitter, appconfig::get_findsplitter_size_list(), appconfig::get_hspl_size_list(), appconfig::get_mainwingeometry(), appconfig::get_vspl_size_list(), hspl, mytetraconfig, and vspl.
Referenced by main().
void mainwindow::restore_tree_position (void)
Definition at line 124 of file mainwindow.cpp.
References appconfig::get_tree_position(), mytetraconfig, and set_tree_position().
Referenced by main().
void mainwindow::restore_recordtable_position (void)
Definition at line 161 of file mainwindow.cpp.
References appconfig::get_recordtable_position(), mytetraconfig, and set_recordtable_position().
Referenced by main().
void mainwindow::restore_findonbase_visible (void)
Definition at line 183 of file mainwindow.cpp.
References appconfig::get_findscreen_show(), and mytetraconfig.
Referenced by main().
void mainwindow::set_tree_position (QStringList path)
Definition at line 146 of file mainwindow.cpp.
References TreeItem::data(), knowtreemodel::get_item_index(), TreeModel::getItem(), treescreen::kntrmodel, treescreen::set_cursor_to_index(), and treeview.
Referenced by restore_tree_position().
void mainwindow::set_recordtable_position (int n)
Definition at line 177 of file mainwindow.cpp.
References recordtableview, and recordtablescreen::set_selection_to_pos().
Referenced by restore_recordtable_position().
void mainwindow::fileNew (void) [private, slot]
Definition at line 264 of file mainwindow.cpp.
Referenced by initFileActions().
void mainwindow::fileOpen (void) [private, slot]
Definition at line 270 of file mainwindow.cpp.
Referenced by initFileActions().
bool mainwindow::fileSave (void) [private, slot]
Definition at line 276 of file mainwindow.cpp.
Referenced by initFileActions().
bool mainwindow::fileSaveAs (void) [private, slot]
Definition at line 282 of file mainwindow.cpp.
Referenced by initFileActions().
void mainwindow::filePrint (void) [private, slot]
Definition at line 288 of file mainwindow.cpp.
References editorview, and editor::textarea.
Referenced by initFileActions().
void mainwindow::filePrintPreview (void) [private, slot]
Definition at line 303 of file mainwindow.cpp.
References editorview, and editor::textarea.
Referenced by initFileActions().
void mainwindow::filePrintPdf (void) [private, slot]
Definition at line 311 of file mainwindow.cpp.
References editorview, and editor::textarea.
Referenced by initFileActions().
void mainwindow::icon_activated (QSystemTrayIcon::ActivationReason reason) [private, slot]
Definition at line 378 of file mainwindow.cpp.
Referenced by set_icon().
void mainwindow::application_exit (void) [private, slot]
Definition at line 328 of file mainwindow.cpp.
Referenced by initFileActions().
void mainwindow::setup_ui (void) [private]
Definition at line 43 of file mainwindow.cpp.
References editorview, findscreendisp, recordtableview, statbar, and treeview.
Referenced by mainwindow().
void mainwindow::setup_signals (void) [private]
Definition at line 64 of file mainwindow.cpp.
Referenced by mainwindow().
void mainwindow::assembly (void) [private]
Definition at line 70 of file mainwindow.cpp.
References editorview, findscreendisp, findsplitter, hspl, recordtableview, treeview, and vspl.
Referenced by mainwindow().
void mainwindow::initFileActions (void) [private]
Definition at line 198 of file mainwindow.cpp.
References application_exit(), fileNew(), fileOpen(), filePrint(), filePrintPdf(), filePrintPreview(), fileSave(), and fileSaveAs().
Referenced by mainwindow().
void mainwindow::initRecordTableActions (void) [private]
void mainwindow::setup_icon_actions (void) [private]
Definition at line 334 of file mainwindow.cpp.
References tray_maximize_action, tray_minimize_action, tray_quit_action, and tray_restore_action.
Referenced by mainwindow().
void mainwindow::create_tray_icon (void) [private]
Definition at line 350 of file mainwindow.cpp.
References tray_icon, tray_icon_menu, tray_maximize_action, tray_minimize_action, tray_quit_action, and tray_restore_action.
Referenced by mainwindow().
void mainwindow::set_icon (void) [private]
Definition at line 364 of file mainwindow.cpp.
References icon_activated(), and tray_icon.
Referenced by mainwindow().
void mainwindow::save_geometry (void) [private]
Definition at line 109 of file mainwindow.cpp.
References findscreendisp, findsplitter, hspl, mytetraconfig, appconfig::set_findsplitter_size_list(), appconfig::set_hspl_size_list(), appconfig::set_mainwingeometry(), appconfig::set_vspl_size_list(), and vspl.
Referenced by ~mainwindow().
void mainwindow::save_tree_position (void) [private]
Definition at line 133 of file mainwindow.cpp.
References treescreen::get_current_item_index(), TreeItem::get_path(), TreeModel::getItem(), treescreen::kntrmodel, mytetraconfig, appconfig::set_tree_position(), and treeview.
Referenced by ~mainwindow().
void mainwindow::save_recordtable_position (void) [private]
Definition at line 169 of file mainwindow.cpp.
References recordtablescreen::get_first_selection_pos(), mytetraconfig, recordtableview, and appconfig::set_recordtable_position().
Referenced by ~mainwindow().
void mainwindow::closeEvent (QCloseEvent * event) [protected]
Definition at line 401 of file mainwindow.cpp.
References tray_icon.
Member Data Documentation
treescreen* mainwindow::treeview
Definition at line 79 of file mainwindow.h.
Referenced by assembly(), save_tree_position(), set_tree_position(), setup_ui(), and ~mainwindow().
recordtablescreen* mainwindow::recordtableview
Definition at line 80 of file mainwindow.h.
Referenced by assembly(), save_current_record_text(), save_recordtable_position(), set_recordtable_position(), setup_ui(), and ~mainwindow().
metaeditor* mainwindow::editorview
Definition at line 81 of file mainwindow.h.
Referenced by assembly(), filePrint(), filePrintPdf(), filePrintPreview(), save_current_record_text(), setup_ui(), and ~mainwindow().
findscreen* mainwindow::findscreendisp
Definition at line 82 of file mainwindow.h.
Referenced by assembly(), save_geometry(), and setup_ui().
QStatusBar* mainwindow::statbar
Definition at line 83 of file mainwindow.h.
Referenced by setup_ui().
QAction* mainwindow::tray_restore_action [private]
Definition at line 125 of file mainwindow.h.
Referenced by create_tray_icon(), and setup_icon_actions().
QAction* mainwindow::tray_maximize_action [private]
Definition at line 126 of file mainwindow.h.
Referenced by create_tray_icon(), and setup_icon_actions().
QAction* mainwindow::tray_minimize_action [private]
Definition at line 127 of file mainwindow.h.
Referenced by create_tray_icon(), and setup_icon_actions().
QAction* mainwindow::tray_quit_action [private]
Definition at line 128 of file mainwindow.h.
Referenced by create_tray_icon(), and setup_icon_actions().
QSystemTrayIcon* mainwindow::tray_icon [private]
Definition at line 130 of file mainwindow.h.
Referenced by closeEvent(), create_tray_icon(), mainwindow(), and set_icon().
QMenu* mainwindow::tray_icon_menu [private]
Definition at line 131 of file mainwindow.h.
Referenced by create_tray_icon().
QSplitter* mainwindow::vspl [private]
Definition at line 133 of file mainwindow.h.
Referenced by assembly(), restore_geometry(), and save_geometry().
QSplitter* mainwindow::hspl [private]
Definition at line 134 of file mainwindow.h.
Referenced by assembly(), restore_geometry(), and save_geometry().
QSplitter* mainwindow::findsplitter [private]
Definition at line 135 of file mainwindow.h.
Referenced by assembly(), restore_geometry(), and save_geometry().
The documentation for this class was generated from the following files:
mainwindow.h
mainwindow.cpp