recordtabledata Class Reference
#include <recordtabledata.h>
Public Member Functions
recordtabledata (QObject *pobj=0)
virtual ~recordtabledata ()
QString get_text (int pos) const
QString get_field (QString name, int pos) const
void set_field (QString name, QString value, int pos)
QMap< QString, QString > get_fields (int pos) const
QMap< QString, QString > get_record_img (int pos) const
void init (QDomElement dommodel)
void clear (void)
int size (void)
QDomDocument export_data_to_dom (void)
int insert_new_record (int mode, int pos, QString name, QString author, QString url, QString tags, QString text)
void edit_record (int pos, QString name, QString author, QString url, QString tags)
void delete_record (int i)
void delete_records (QVector< int > delidx)
void moveup (int pos)
void movedn (int pos)
Private Types
typedef QMap< QString, QString > reclintype
Private Member Functions
void setup_data_from_dom (QDomElement *dommodel)
Private Attributes
QList< reclintype > table
Detailed Description
Definition at line 11 of file recordtabledata.h.
Member Typedef Documentation
typedef QMap<QString, QString> recordtabledata::reclintype [private]
Definition at line 67 of file recordtabledata.h.
Constructor & Destructor Documentation
recordtabledata::recordtabledata (QObject * pobj = 0)
Definition at line 12 of file recordtabledata.cpp.
recordtabledata::~recordtabledata () [virtual]
Definition at line 19 of file recordtabledata.cpp.
Member Function Documentation
QString recordtabledata::get_text (int pos) const
Definition at line 66 of file recordtabledata.cpp.
References critical_error(), appconfig::get_tetradir(), mytetraconfig, and table.
Referenced by get_record_img().
QString recordtabledata::get_field (QString name, int pos) const
Definition at line 26 of file recordtabledata.cpp.
References critical_error(), and table.
Referenced by recordtablemodel::data(), delete_record(), recordtablescreen::edit_field_context(), and recordtablescreen::select().
void recordtabledata::set_field (QString name, QString value, int pos)
Definition at line 50 of file recordtabledata.cpp.
References critical_error(), and table.
Referenced by recordtablemodel::setData().
QMap< QString, QString > recordtabledata::get_fields (int pos) const
Definition at line 94 of file recordtabledata.cpp.
References critical_error(), and table.
Referenced by get_record_img().
QMap< QString, QString > recordtabledata::get_record_img (int pos) const
Definition at line 128 of file recordtabledata.cpp.
References get_fields(), get_text(), and table.
Referenced by recordtablescreen::copy().
void recordtabledata::init (QDomElement dommodel)
Definition at line 144 of file recordtabledata.cpp.
References setup_data_from_dom().
Referenced by TreeItem::recordtable_init().
void recordtabledata::clear (void)
Definition at line 414 of file recordtabledata.cpp.
References delete_records(), and table.
Referenced by TreeItem::recordtable_clear().
int recordtabledata::size (void)
Definition at line 425 of file recordtabledata.cpp.
References table.
Referenced by recordtablescreen::delete_records(), TreeItem::recordtable_getrowcount(), and recordtablemodel::rowCount().
QDomDocument recordtabledata::export_data_to_dom (void)
Definition at line 208 of file recordtabledata.cpp.
References table.
Referenced by TreeItem::recordtable_export_data_to_dom().
int recordtabledata::insert_new_record (int mode, int pos, QString name, QString author, QString url, QString tags, QString text)
Definition at line 249 of file recordtabledata.cpp.
References ADD_NEW_RECORD_AFTER, ADD_NEW_RECORD_BEFORE, ADD_NEW_RECORD_TO_END, critical_error(), appconfig::get_lastidnum(), appconfig::get_lastnotenum_as_line(), appconfig::get_tetradir(), appconfig::inc_lastidnum(), appconfig::inc_lastnotenum(), mytetraconfig, and table.
Referenced by recordtablescreen::add_new().
void recordtabledata::edit_record (int pos, QString name, QString author, QString url, QString tags)
Definition at line 349 of file recordtabledata.cpp.
References table.
Referenced by recordtablescreen::edit_field().
void recordtabledata::delete_record (int i)
Definition at line 377 of file recordtabledata.cpp.
References get_field(), appconfig::get_tetradir(), mytetraconfig, remove_dir(), and table.
Referenced by delete_records().
void recordtabledata::delete_records (QVector< int > delidx)
Definition at line 402 of file recordtabledata.cpp.
References delete_record().
Referenced by clear(), and recordtablescreen::delete_records().
void recordtabledata::moveup (int pos)
Definition at line 432 of file recordtabledata.cpp.
References table.
Referenced by recordtablescreen::moveup().
void recordtabledata::movedn (int pos)
Definition at line 448 of file recordtabledata.cpp.
References table.
Referenced by recordtablescreen::movedn().
void recordtabledata::setup_data_from_dom (QDomElement * dommodel) [private]
Definition at line 157 of file recordtabledata.cpp.
References table.
Referenced by init().
Member Data Documentation
QList< reclintype > recordtabledata::table [private]
Definition at line 68 of file recordtabledata.h.
Referenced by clear(), delete_record(), edit_record(), export_data_to_dom(), get_field(), get_fields(), get_record_img(), get_text(), insert_new_record(), movedn(), moveup(), set_field(), setup_data_from_dom(), and size().
The documentation for this class was generated from the following files:
recordtabledata.h
recordtabledata.cpp