editor Class Reference
#include <editor.h>
Public Member Functions
editor (int mode, QWidget *parent=0)
~editor (void)
void set_textarea (QString text)
void set_textarea_editable (bool editable)
QString get_textarea (void)
Public Attributes
QToolButton * bold
QToolButton * italic
QToolButton * underline
QToolButton * numericlist
QToolButton * dotlist
QToolButton * indentplus
QToolButton * indentminus
QFontComboBox * fontselect
QSpinBox * fontsize
QToolButton * showhtml
QLabel * infoarea
QTextEdit * textarea
QHBoxLayout * textformat_buttons_layout
QVBoxLayout * buttons_and_edit_layout
Private Slots
void on_bold_clicked (void)
void on_italic_clicked (void)
void on_underline_clicked (void)
void on_numericlist_clicked (void)
void on_dotlist_clicked (void)
void on_indentplus_clicked (void)
void on_indentminus_clicked (void)
void on_showhtml_clicked (void)
Private Member Functions
void setup_signals (void)
void setup_buttons (void)
void setup_editor_area (void)
void assembly_buttons (void)
void assembly (void)
void format_to_list (QTextListFormat::Style setformat)
Detailed Description
Definition at line 16 of file editor.h.
Constructor & Destructor Documentation
editor::editor (int mode, QWidget * parent = 0)
Definition at line 11 of file editor.cpp.
References assembly(), assembly_buttons(), ENABLE_ASSEMBLY, setup_buttons(), setup_editor_area(), and setup_signals().
editor::~editor (void)
Definition at line 25 of file editor.cpp.
Member Function Documentation
void editor::set_textarea (QString text)
Definition at line 187 of file editor.cpp.
References textarea.
Referenced by metaeditor::clear_all(), and recordtablescreen::select().
void editor::set_textarea_editable (bool editable)
Definition at line 194 of file editor.cpp.
References textarea.
QString editor::get_textarea (void)
Definition at line 222 of file editor.cpp.
References textarea.
Referenced by addnewrecord::get_field().
void editor::on_bold_clicked (void) [private, slot]
Definition at line 232 of file editor.cpp.
References textarea.
Referenced by setup_signals().
void editor::on_italic_clicked (void) [private, slot]
Definition at line 241 of file editor.cpp.
References textarea.
Referenced by setup_signals().
void editor::on_underline_clicked (void) [private, slot]
Definition at line 250 of file editor.cpp.
References textarea.
Referenced by setup_signals().
void editor::on_numericlist_clicked (void) [private, slot]
Definition at line 282 of file editor.cpp.
References format_to_list().
Referenced by setup_signals().
void editor::on_dotlist_clicked (void) [private, slot]
Definition at line 289 of file editor.cpp.
References format_to_list().
Referenced by setup_signals().
void editor::on_indentplus_clicked (void) [private, slot]
Definition at line 296 of file editor.cpp.
References textarea.
Referenced by setup_signals().
void editor::on_indentminus_clicked (void) [private, slot]
Definition at line 313 of file editor.cpp.
References textarea.
Referenced by setup_signals().
void editor::on_showhtml_clicked (void) [private, slot]
Definition at line 333 of file editor.cpp.
References info_window(), and textarea.
Referenced by setup_signals().
void editor::setup_signals (void) [private]
Definition at line 32 of file editor.cpp.
References bold, dotlist, indentminus, indentplus, italic, numericlist, on_bold_clicked(), on_dotlist_clicked(), on_indentminus_clicked(), on_indentplus_clicked(), on_italic_clicked(), on_numericlist_clicked(), on_showhtml_clicked(), on_underline_clicked(), showhtml, and underline.
Referenced by editor().
void editor::setup_buttons (void) [private]
Definition at line 46 of file editor.cpp.
References bold, dotlist, fontselect, fontsize, indentminus, indentplus, italic, numericlist, showhtml, and underline.
Referenced by editor().
void editor::setup_editor_area (void) [private]
Definition at line 134 of file editor.cpp.
References textarea.
Referenced by editor().
void editor::assembly_buttons (void) [private]
Definition at line 143 of file editor.cpp.
References bold, dotlist, fontselect, fontsize, indentminus, indentplus, italic, numericlist, showhtml, textformat_buttons_layout, and underline.
Referenced by editor().
void editor::assembly (void) [private]
Definition at line 163 of file editor.cpp.
References buttons_and_edit_layout, textarea, and textformat_buttons_layout.
Referenced by editor().
void editor::format_to_list (QTextListFormat::Style setformat) [private]
Definition at line 258 of file editor.cpp.
References textarea.
Referenced by on_dotlist_clicked(), and on_numericlist_clicked().
Member Data Documentation
QToolButton* editor::bold
Definition at line 25 of file editor.h.
Referenced by assembly_buttons(), setup_buttons(), and setup_signals().
QToolButton* editor::italic
Definition at line 26 of file editor.h.
Referenced by assembly_buttons(), setup_buttons(), and setup_signals().
QToolButton* editor::underline
Definition at line 27 of file editor.h.
Referenced by assembly_buttons(), setup_buttons(), and setup_signals().
QToolButton* editor::numericlist
Definition at line 28 of file editor.h.
Referenced by assembly_buttons(), setup_buttons(), and setup_signals().
QToolButton* editor::dotlist
Definition at line 29 of file editor.h.
Referenced by assembly_buttons(), setup_buttons(), and setup_signals().
QToolButton* editor::indentplus
Definition at line 30 of file editor.h.
Referenced by assembly_buttons(), setup_buttons(), and setup_signals().
QToolButton* editor::indentminus
Definition at line 31 of file editor.h.
Referenced by assembly_buttons(), setup_buttons(), and setup_signals().
QFontComboBox* editor::fontselect
Definition at line 32 of file editor.h.
Referenced by assembly_buttons(), and setup_buttons().
QSpinBox* editor::fontsize
Definition at line 33 of file editor.h.
Referenced by assembly_buttons(), and setup_buttons().
QToolButton* editor::showhtml
Definition at line 34 of file editor.h.
Referenced by assembly_buttons(), setup_buttons(), and setup_signals().
QLabel* editor::infoarea
Definition at line 35 of file editor.h.
QTextEdit* editor::textarea
Definition at line 38 of file editor.h.
Referenced by assembly(), mainwindow::filePrint(), mainwindow::filePrintPdf(), mainwindow::filePrintPreview(), format_to_list(), get_textarea(), metaeditor::meta_assembly(), on_bold_clicked(), on_indentminus_clicked(), on_indentplus_clicked(), on_italic_clicked(), on_showhtml_clicked(), on_underline_clicked(), mainwindow::save_current_record_text(), set_textarea(), set_textarea_editable(), and setup_editor_area().
QHBoxLayout* editor::textformat_buttons_layout
Definition at line 41 of file editor.h.
Referenced by assembly(), assembly_buttons(), and metaeditor::meta_assembly().
QVBoxLayout* editor::buttons_and_edit_layout
Definition at line 44 of file editor.h.
Referenced by assembly().
The documentation for this class was generated from the following files:
editor.h
editor.cpp