metaeditor Class Reference
#include <metaeditor.h>
Public Slots
void set_field (QString n, QString v)
void clear_all (void)
Public Member Functions
metaeditor (void)
~metaeditor (void)
void set_name (QString name)
void set_author (QString author)
void set_url (QString url)
void set_tags (QString tags)
Private Member Functions
void setup_labels (void)
void meta_assembly (void)
Private Attributes
QLabel * record_name
QLabel * record_author
QLabel * label_url
QLabel * record_url
QLabel * label_tags
QLabel * record_tags
QGridLayout * metaeditor_assembly_layout
Detailed Description
Definition at line 12 of file metaeditor.h.
Constructor & Destructor Documentation
metaeditor::metaeditor (void)
Definition at line 5 of file metaeditor.cpp.
References meta_assembly(), and setup_labels().
metaeditor::~metaeditor (void)
Definition at line 12 of file metaeditor.cpp.
Member Function Documentation
void metaeditor::set_field (QString n, QString v) [slot]
Definition at line 89 of file metaeditor.cpp.
References critical_error(), set_author(), set_name(), set_tags(), and set_url().
void metaeditor::clear_all (void) [slot]
Definition at line 100 of file metaeditor.cpp.
References set_author(), set_name(), set_tags(), editor::set_textarea(), and set_url().
void metaeditor::set_name (QString name)
Definition at line 110 of file metaeditor.cpp.
References record_name.
Referenced by clear_all(), recordtablescreen::edit_field(), recordtablescreen::select(), and set_field().
void metaeditor::set_author (QString author)
Definition at line 117 of file metaeditor.cpp.
References record_author.
Referenced by clear_all(), recordtablescreen::edit_field(), recordtablescreen::select(), and set_field().
void metaeditor::set_url (QString url)
Definition at line 132 of file metaeditor.cpp.
References label_url, and record_url.
Referenced by clear_all(), recordtablescreen::edit_field(), recordtablescreen::select(), and set_field().
void metaeditor::set_tags (QString tags)
Definition at line 160 of file metaeditor.cpp.
References label_tags, and record_tags.
Referenced by clear_all(), recordtablescreen::edit_field(), recordtablescreen::select(), and set_field().
void metaeditor::setup_labels (void) [private]
Definition at line 17 of file metaeditor.cpp.
References label_tags, label_url, record_author, record_name, record_tags, and record_url.
Referenced by metaeditor().
void metaeditor::meta_assembly (void) [private]
Definition at line 59 of file metaeditor.cpp.
References label_tags, label_url, metaeditor_assembly_layout, record_author, record_name, record_tags, record_url, editor::textarea, and editor::textformat_buttons_layout.
Referenced by metaeditor().
Member Data Documentation
QLabel* metaeditor::record_name [private]
Definition at line 33 of file metaeditor.h.
Referenced by meta_assembly(), set_name(), and setup_labels().
QLabel* metaeditor::record_author [private]
Definition at line 34 of file metaeditor.h.
Referenced by meta_assembly(), set_author(), and setup_labels().
QLabel* metaeditor::label_url [private]
Definition at line 36 of file metaeditor.h.
Referenced by meta_assembly(), set_url(), and setup_labels().
QLabel* metaeditor::record_url [private]
Definition at line 37 of file metaeditor.h.
Referenced by meta_assembly(), set_url(), and setup_labels().
QLabel* metaeditor::label_tags [private]
Definition at line 39 of file metaeditor.h.
Referenced by meta_assembly(), set_tags(), and setup_labels().
QLabel* metaeditor::record_tags [private]
Definition at line 40 of file metaeditor.h.
Referenced by meta_assembly(), set_tags(), and setup_labels().
QGridLayout* metaeditor::metaeditor_assembly_layout [private]
Definition at line 43 of file metaeditor.h.
Referenced by meta_assembly().
The documentation for this class was generated from the following files:
metaeditor.h
metaeditor.cpp