clipbrecords Class Reference
#include <clipbrecords.h>
Public Member Functions
clipbrecords (void)
~clipbrecords (void)
void init (void)
void add_record (QMap< QString, QString > record)
void print (void) const
int get_records_num (void) const
QMap< QString, QString > get_record (int n) const
QStringList formats () const
Protected Member Functions
QVariant retrieveData (const QString &format, QVariant::Type preferredType) const
Private Attributes
clipb_records_struct records
QStringList clipb_records_formats
Detailed Description
Definition at line 18 of file clipbrecords.h.
Constructor & Destructor Documentation
clipbrecords::clipbrecords (void)
Definition at line 11 of file clipbrecords.cpp.
References init().
clipbrecords::~clipbrecords (void)
Definition at line 17 of file clipbrecords.cpp.
Member Function Documentation
void clipbrecords::init (void)
Definition at line 23 of file clipbrecords.cpp.
References clipb_records_formats, records, and clipb_records_struct::table.
Referenced by clipbrecords().
void clipbrecords::add_record (QMap< QString, QString > record)
Definition at line 32 of file clipbrecords.cpp.
References records, and clipb_records_struct::table.
Referenced by recordtablescreen::copy().
void clipbrecords::print (void) const
Definition at line 38 of file clipbrecords.cpp.
References records, and clipb_records_struct::table.
Referenced by recordtablescreen::copy(), and recordtablescreen::paste().
int clipbrecords::get_records_num (void) const
Definition at line 60 of file clipbrecords.cpp.
References records, and clipb_records_struct::table.
Referenced by recordtablescreen::paste().
QMap< QString, QString > clipbrecords::get_record (int n) const
Definition at line 67 of file clipbrecords.cpp.
References critical_error(), records, and clipb_records_struct::table.
Referenced by recordtablescreen::paste().
QStringList clipbrecords::formats () const
Definition at line 79 of file clipbrecords.cpp.
References clipb_records_formats.
QVariant clipbrecords::retrieveData (const QString & format, QVariant::Type preferredType) const [protected]
Definition at line 85 of file clipbrecords.cpp.
References records.
Member Data Documentation
clipb_records_struct clipbrecords::records [private]
Definition at line 41 of file clipbrecords.h.
Referenced by add_record(), get_record(), get_records_num(), init(), print(), and retrieveData().
QStringList clipbrecords::clipb_records_formats [private]
Definition at line 42 of file clipbrecords.h.
Referenced by formats(), and init().
The documentation for this class was generated from the following files:
clipbrecords.h
clipbrecords.cpp