main.cpp File Reference
#include `main.h`
#include `mainwindow.h`
#include `appconfig.h`
#include `clipbrecords.h`
Functions
void logprint (char *lpszText,...)
void critical_error (QString message)
void info_window (QString i)
QString xmlnode_to_string (QDomNode xmldata)
QString convert_to_lastnumformat (int n)
void remove_dir (QString namedirfrom)
char * fromQStringToChar (const QString &str)
void print_object_tree_recurse (QObject *pobj)
void print_object_tree (void)
bool compare_QStringList_len (const QStringList &list1, const QStringList &list2)
int imax (int x1, int x2)
int imin (int x1, int x2)
int main (int argc, char **argv)
Variables
appconfig mytetraconfig
QObject * mainwindowpointer
Function Documentation
bool compare_QStringList_len (const QStringList & list1, const QStringList & list2)
Definition at line 223 of file main.cpp.
QString convert_to_lastnumformat (int n)
Definition at line 107 of file main.cpp.
void critical_error (QString message)
Definition at line 42 of file main.cpp.
Referenced by appconfig::appconfig(), TreeItem::data(), recordtabledata::get_field(), infofieldenter::get_field(), editrecord::get_field(), recordtabledata::get_fields(), appconfig::get_parameter(), clipbrecords::get_record(), recordtabledata::get_text(), TreeModel::getItem(), recordtabledata::insert_new_record(), recordtablescreen::select(), appconfig::set_addnewrecord_expand_info(), recordtabledata::set_field(), metaeditor::set_field(), infofieldenter::set_field(), and editrecord::set_field().
char* fromQStringToChar (const QString & str)
Definition at line 167 of file main.cpp.
Referenced by print_object_tree_recurse().
int imax (int x1, int x2)
Definition at line 229 of file main.cpp.
int imin (int x1, int x2)
Definition at line 236 of file main.cpp.
Referenced by findscreen::setup_toolsline(), and infofieldenter::setup_ui().
void info_window (QString i)
Definition at line 50 of file main.cpp.
Referenced by editor::on_showhtml_clicked().
void logprint (char * lpszText, ...)
Definition at line 12 of file main.cpp.
int main (int argc, char ** argv)
Definition at line 243 of file main.cpp.
References DPF, GAME_RELEASE, GAME_RELEASE_VERSION, mainwindowpointer, print_object_tree(), mainwindow::restore_findonbase_visible(), mainwindow::restore_geometry(), mainwindow::restore_recordtable_position(), and mainwindow::restore_tree_position().
void print_object_tree (void)
Definition at line 214 of file main.cpp.
References mainwindowpointer, and print_object_tree_recurse().
Referenced by main().
void print_object_tree_recurse (QObject * pobj)
Definition at line 185 of file main.cpp.
References fromQStringToChar().
Referenced by print_object_tree().
void remove_dir (QString namedirfrom)
Definition at line 125 of file main.cpp.
References appconfig::get_lastprefixnum_as_line(), appconfig::get_trashdir(), appconfig::inc_lastprefixnum(), and mytetraconfig.
Referenced by recordtabledata::delete_record().
QString xmlnode_to_string (QDomNode xmldata)
Definition at line 73 of file main.cpp.
Variable Documentation
QObject* mainwindowpointer
Definition at line 10 of file main.cpp.
Referenced by find_object(), main(), and print_object_tree().
appconfig mytetraconfig
Definition at line 7 of file main.cpp.