main.h File Reference
#include <stdio.h>
#include <QApplication>
#include <QClipboard>
#include <QObject>
#include <QWidget>
#include <QDialog>
#include <QtGlobal>
#include <QDomNode>
#include <QTreeView>
#include <QTextEdit>
#include <QPushButton>
#include <QVBoxLayout>
#include <QSizePolicy>
#include `mainwindow.h`
Defines
#define GAME_RELEASE_VERSION 0
#define GAME_RELEASE 114
#define COMPILE_MODE 0
#define DEBUG_PRINT
#define CURRENT_FORMAT_VERSION 1
#define CURRENT_FORMAT_SUBVERSION 1
#define DPF(X) logprint X
Functions
void logprint (char *lpszText,...)
void critical_error (QString message)
void info_window (QString i)
QString xmlnode_to_string (QDomNode xmldata)
QString convert_to_lastnumformat (int n)
void remove_dir (QString namedirfrom)
void print_object_tree (void)
bool compare_QStringList_len (const QStringList &list1, const QStringList &list2)
int imax (int x1, int x2)
int imin (int x1, int x2)
template<class X> X * find_object (QString n)
Define Documentation
#define COMPILE_MODE 0
Definition at line 73 of file main.h.
#define CURRENT_FORMAT_SUBVERSION 1
Definition at line 87 of file main.h.
Referenced by treescreen::save_knowtree().
#define CURRENT_FORMAT_VERSION 1
Definition at line 86 of file main.h.
Referenced by treescreen::save_knowtree().
#define DEBUG_PRINT
Definition at line 79 of file main.h.
#define DPF(X) logprint X
Definition at line 91 of file main.h.
Referenced by main().
#define GAME_RELEASE 114
Definition at line 68 of file main.h.
Referenced by main().
#define GAME_RELEASE_VERSION 0
Definition at line 67 of file main.h.
Referenced by main().
Function Documentation
bool compare_QStringList_len (const QStringList & list1, const QStringList & list2)
Definition at line 223 of file main.cpp.
QString convert_to_lastnumformat (int n)
Definition at line 107 of file main.cpp.
void critical_error (QString message)
Definition at line 42 of file main.cpp.
Referenced by appconfig::appconfig(), TreeItem::data(), editrecord::get_field(), infofieldenter::get_field(), recordtabledata::get_field(), recordtabledata::get_fields(), appconfig::get_parameter(), clipbrecords::get_record(), recordtabledata::get_text(), TreeModel::getItem(), recordtabledata::insert_new_record(), recordtablescreen::select(), appconfig::set_addnewrecord_expand_info(), editrecord::set_field(), infofieldenter::set_field(), metaeditor::set_field(), and recordtabledata::set_field().
template<class X> X* find_object (QString n) [inline]
Definition at line 112 of file main.h.
References mainwindowpointer.
int imax (int x1, int x2)
Definition at line 229 of file main.cpp.
int imin (int x1, int x2)
Definition at line 236 of file main.cpp.
Referenced by findscreen::setup_toolsline(), and infofieldenter::setup_ui().
void info_window (QString i)
Definition at line 50 of file main.cpp.
Referenced by editor::on_showhtml_clicked().
void logprint (char * lpszText, ...)
Definition at line 12 of file main.cpp.
void print_object_tree (void)
Definition at line 214 of file main.cpp.
References mainwindowpointer, and print_object_tree_recurse().
Referenced by main().
void remove_dir (QString namedirfrom)
Definition at line 125 of file main.cpp.
References appconfig::get_lastprefixnum_as_line(), appconfig::get_trashdir(), appconfig::inc_lastprefixnum(), and mytetraconfig.
Referenced by recordtabledata::delete_record().
QString xmlnode_to_string (QDomNode xmldata)
Definition at line 73 of file main.cpp.