treescreen Class Reference
#include <treescreen.h>
Public Member Functions
treescreen (QWidget *parent=0)
virtual ~treescreen ()
void save_knowtree (void)
void update_selected_branch (void)
int get_first_selected_item_index (void)
QModelIndex get_current_item_index (void)
QItemSelectionModel * get_selection_model (void)
void set_cursor_to_index (QModelIndex index)
treescreen (QWidget *parent=0)
virtual ~treescreen ()
void save_knowtree (void)
void update_selected_branch (void)
QItemSelectionModel * get_selection_model (void)
Public Attributes
knowtreemodel * kntrmodel
knowtreemodel * kntrmodel
Private Slots
void expand_all_subbranch (void)
void collapse_all_subbranch (void)
void expand_or_collapse_recurse (QModelIndex index, bool mode)
void ins_subbranch (void)
void ins_branch (void)
void edit_branch (void)
void del_branch (void)
void move_up_branch (void)
void move_dn_branch (void)
void on_knowtree_clicked (const QModelIndex &index)
void on_customContextMenuRequested (const QPoint &pos)
void expand_all_subbranch (void)
void collapse_all_subbranch (void)
void expand_or_collapse_recurse (QModelIndex index, bool mode)
void ins_subbranch (void)
void ins_branch (void)
void edit_branch (void)
void del_branch (void)
void on_knowtree_clicked (const QModelIndex &index)
Private Member Functions
void setup_ui (void)
void setup_signals (void)
void setup_actions (void)
void assembly (void)
void init_knowtree (void)
void insert_new_branch (void)
void move_updn_branch (int direction)
bool move_check_enable (void)
void setup_ui (void)
void setup_signals (void)
void setup_actions (void)
void assembly (void)
void init_knowtree (void)
void insert_new_branch (void)
int get_first_selected_item_index (void)
QModelIndex get_current_item_index (void)
Private Attributes
QToolBar * tools_line
QTreeView * knowtree
QVBoxLayout * treescreen_layout
QAction * action_expand_all_subbranch
QAction * action_collapse_all_subbranch
QAction * action_ins_branch
QAction * action_ins_subbranch
QAction * action_edit_branch
QAction * action_del_branch
QAction * action_move_up_branch
QAction * action_move_dn_branch
QToolBar * tools_line
QTreeView * knowtree
QVBoxLayout * treescreen_layout
QAction * action_expand_all_subbranch
QAction * action_collapse_all_subbranch
QAction * action_ins_branch
QAction * action_ins_subbranch
QAction * action_edit_branch
QAction * action_del_branch
Detailed Description
Definition at line 16 of file treescreen.h.
Constructor & Destructor Documentation
treescreen::treescreen (QWidget * parent = 0)
Definition at line 11 of file treescreen.cpp.
References assembly(), init_knowtree(), knowtree, setup_actions(), setup_signals(), and setup_ui().
treescreen::~treescreen () [virtual]
Definition at line 27 of file treescreen.cpp.
treescreen::treescreen (QWidget * parent = 0)
virtual treescreen::~treescreen () [virtual]
Member Function Documentation
void treescreen::save_knowtree (void)
Definition at line 600 of file treescreen.cpp.
References CURRENT_FORMAT_SUBVERSION, CURRENT_FORMAT_VERSION, knowtreemodel::export_fullmodeldata_to_dom(), appconfig::get_lastprefixnum_as_line(), appconfig::get_tetradir(), appconfig::get_trashdir(), appconfig::inc_lastprefixnum(), kntrmodel, mytetraconfig, and TreeModel::rootItem.
Referenced by del_branch(), edit_branch(), ins_branch(), ins_subbranch(), and move_updn_branch().
void treescreen::update_selected_branch (void)
Definition at line 650 of file treescreen.cpp.
References knowtree.
int treescreen::get_first_selected_item_index (void)
Definition at line 674 of file treescreen.cpp.
References knowtree.
QModelIndex treescreen::get_current_item_index (void)
Definition at line 687 of file treescreen.cpp.
References knowtree.
Referenced by del_branch(), edit_branch(), ins_branch(), ins_subbranch(), move_updn_branch(), and mainwindow::save_tree_position().
QItemSelectionModel * treescreen::get_selection_model (void)
Definition at line 661 of file treescreen.cpp.
References knowtree.
void treescreen::set_cursor_to_index (QModelIndex index)
Definition at line 667 of file treescreen.cpp.
References knowtree.
Referenced by mainwindow::set_tree_position().
void treescreen::expand_all_subbranch (void) [private, slot]
Definition at line 170 of file treescreen.cpp.
References expand_or_collapse_recurse(), and knowtree.
Referenced by setup_actions().
void treescreen::collapse_all_subbranch (void) [private, slot]
Definition at line 180 of file treescreen.cpp.
References expand_or_collapse_recurse(), and knowtree.
Referenced by setup_actions().
void treescreen::expand_or_collapse_recurse (QModelIndex index, bool mode) [private, slot]
Definition at line 190 of file treescreen.cpp.
References knowtree.
Referenced by collapse_all_subbranch(), and expand_all_subbranch().
void treescreen::ins_subbranch (void) [private, slot]
Definition at line 261 of file treescreen.cpp.
References knowtreemodel::add_new_child_branch(), TreeItem::childCount(), get_current_item_index(), appconfig::get_lastidnum(), TreeModel::getItem(), appconfig::inc_lastidnum(), knowtreemodel::indexChildren(), knowtree, kntrmodel, mytetraconfig, and save_knowtree().
Referenced by setup_actions().
void treescreen::ins_branch (void) [private, slot]
Definition at line 339 of file treescreen.cpp.
References knowtreemodel::add_new_sibling_branch(), TreeItem::childCount(), get_current_item_index(), appconfig::get_lastidnum(), TreeModel::getItem(), appconfig::inc_lastidnum(), TreeModel::index(), knowtree, kntrmodel, mytetraconfig, TreeItem::parent(), and save_knowtree().
Referenced by setup_actions().
void treescreen::edit_branch (void) [private, slot]
Definition at line 414 of file treescreen.cpp.
References TreeItem::data(), get_current_item_index(), TreeModel::getItem(), knowtree, kntrmodel, save_knowtree(), and TreeItem::setData().
Referenced by setup_actions(), and setup_signals().
void treescreen::del_branch (void) [private, slot]
Definition at line 465 of file treescreen.cpp.
References TreeItem::data(), get_current_item_index(), TreeModel::getItem(), knowtree, kntrmodel, and save_knowtree().
Referenced by setup_actions().
void treescreen::move_up_branch (void) [private, slot]
Definition at line 204 of file treescreen.cpp.
References move_updn_branch().
Referenced by setup_actions().
void treescreen::move_dn_branch (void) [private, slot]
Definition at line 210 of file treescreen.cpp.
References move_updn_branch().
Referenced by setup_actions().
void treescreen::on_knowtree_clicked (const QModelIndex & index) [private, slot]
Definition at line 549 of file treescreen.cpp.
References TreeModel::getItem(), knowtree, kntrmodel, and TreeItem::recordtable_gettabledata().
Referenced by setup_signals().
void treescreen::on_customContextMenuRequested (const QPoint & pos) [private, slot]
Definition at line 113 of file treescreen.cpp.
References action_collapse_all_subbranch, action_del_branch, action_edit_branch, action_expand_all_subbranch, action_ins_branch, action_ins_subbranch, and knowtree.
Referenced by setup_signals().
void treescreen::setup_ui (void) [private]
Definition at line 87 of file treescreen.cpp.
References action_collapse_all_subbranch, action_del_branch, action_edit_branch, action_expand_all_subbranch, action_ins_branch, action_ins_subbranch, action_move_dn_branch, action_move_up_branch, knowtree, and tools_line.
Referenced by treescreen().
void treescreen::setup_signals (void) [private]
Definition at line 133 of file treescreen.cpp.
References edit_branch(), knowtree, on_customContextMenuRequested(), and on_knowtree_clicked().
Referenced by treescreen().
void treescreen::setup_actions (void) [private]
Definition at line 33 of file treescreen.cpp.
References action_collapse_all_subbranch, action_del_branch, action_edit_branch, action_expand_all_subbranch, action_ins_branch, action_ins_subbranch, action_move_dn_branch, action_move_up_branch, collapse_all_subbranch(), del_branch(), edit_branch(), expand_all_subbranch(), ins_branch(), ins_subbranch(), move_dn_branch(), and move_up_branch().
Referenced by treescreen().
void treescreen::assembly (void) [private]
Definition at line 153 of file treescreen.cpp.
References knowtree, tools_line, and treescreen_layout.
Referenced by treescreen().
void treescreen::init_knowtree (void) [private]
Definition at line 579 of file treescreen.cpp.
References xmltree::dommodel, appconfig::get_tetradir(), knowtree, kntrmodel, xmltree::load(), and mytetraconfig.
Referenced by treescreen().
void treescreen::insert_new_branch (void) [private]
Definition at line 407 of file treescreen.cpp.
void treescreen::move_updn_branch (int direction) [private]
Definition at line 216 of file treescreen.cpp.
References get_current_item_index(), knowtree, kntrmodel, move_check_enable(), knowtreemodel::move_dn_branch(), knowtreemodel::move_up_branch(), and save_knowtree().
Referenced by move_dn_branch(), and move_up_branch().
bool treescreen::move_check_enable (void) [private]
Definition at line 241 of file treescreen.cpp.
References knowtree.
Referenced by move_updn_branch().
void treescreen::save_knowtree (void)
void treescreen::update_selected_branch (void)
QItemSelectionModel* treescreen::get_selection_model (void)
void treescreen::expand_all_subbranch (void) [private, slot]
void treescreen::collapse_all_subbranch (void) [private, slot]
void treescreen::expand_or_collapse_recurse (QModelIndex index, bool mode) [private, slot]
void treescreen::ins_subbranch (void) [private, slot]
void treescreen::ins_branch (void) [private, slot]
void treescreen::edit_branch (void) [private, slot]
void treescreen::del_branch (void) [private, slot]
void treescreen::on_knowtree_clicked (const QModelIndex & index) [private, slot]
void treescreen::setup_ui (void) [private]
void treescreen::setup_signals (void) [private]
void treescreen::setup_actions (void) [private]
void treescreen::assembly (void) [private]
void treescreen::init_knowtree (void) [private]
void treescreen::insert_new_branch (void) [private]
int treescreen::get_first_selected_item_index (void) [private]
QModelIndex treescreen::get_current_item_index (void) [private]
Member Data Documentation
knowtreemodel* treescreen::kntrmodel
Definition at line 24 of file treescreen.h.
Referenced by del_branch(), edit_branch(), init_knowtree(), ins_branch(), ins_subbranch(), move_updn_branch(), on_knowtree_clicked(), save_knowtree(), mainwindow::save_tree_position(), and mainwindow::set_tree_position().
QToolBar* treescreen::tools_line [private]
Definition at line 56 of file treescreen.h.
Referenced by assembly(), and setup_ui().
QTreeView* treescreen::knowtree [private]
Definition at line 58 of file treescreen.h.
Referenced by assembly(), collapse_all_subbranch(), del_branch(), edit_branch(), expand_all_subbranch(), expand_or_collapse_recurse(), get_current_item_index(), get_first_selected_item_index(), get_selection_model(), init_knowtree(), ins_branch(), ins_subbranch(), move_check_enable(), move_updn_branch(), on_customContextMenuRequested(), on_knowtree_clicked(), set_cursor_to_index(), setup_signals(), setup_ui(), treescreen(), and update_selected_branch().
QVBoxLayout* treescreen::treescreen_layout [private]
Definition at line 60 of file treescreen.h.
Referenced by assembly().
QAction* treescreen::action_expand_all_subbranch [private]
Definition at line 62 of file treescreen.h.
Referenced by on_customContextMenuRequested(), setup_actions(), and setup_ui().
QAction* treescreen::action_collapse_all_subbranch [private]
Definition at line 63 of file treescreen.h.
Referenced by on_customContextMenuRequested(), setup_actions(), and setup_ui().
QAction* treescreen::action_ins_branch [private]
Definition at line 64 of file treescreen.h.
Referenced by on_customContextMenuRequested(), setup_actions(), and setup_ui().
QAction* treescreen::action_ins_subbranch [private]
Definition at line 65 of file treescreen.h.
Referenced by on_customContextMenuRequested(), setup_actions(), and setup_ui().
QAction* treescreen::action_edit_branch [private]
Definition at line 66 of file treescreen.h.
Referenced by on_customContextMenuRequested(), setup_actions(), and setup_ui().
QAction* treescreen::action_del_branch [private]
Definition at line 67 of file treescreen.h.
Referenced by on_customContextMenuRequested(), setup_actions(), and setup_ui().
QAction* treescreen::action_move_up_branch [private]
Definition at line 68 of file treescreen.h.
Referenced by setup_actions(), and setup_ui().
QAction* treescreen::action_move_dn_branch [private]
Definition at line 69 of file treescreen.h.
Referenced by setup_actions(), and setup_ui().
knowtreemodel* treescreen::kntrmodel
Definition at line 24 of file treescreen_old.h.
QToolBar* treescreen::tools_line [private]
Definition at line 47 of file treescreen_old.h.
QTreeView* treescreen::knowtree [private]
Definition at line 49 of file treescreen_old.h.
QVBoxLayout* treescreen::treescreen_layout [private]
Definition at line 51 of file treescreen_old.h.
QAction* treescreen::action_expand_all_subbranch [private]
Definition at line 53 of file treescreen_old.h.
QAction* treescreen::action_collapse_all_subbranch [private]
Definition at line 54 of file treescreen_old.h.
QAction* treescreen::action_ins_branch [private]
Definition at line 55 of file treescreen_old.h.
QAction* treescreen::action_ins_subbranch [private]
Definition at line 56 of file treescreen_old.h.
QAction* treescreen::action_edit_branch [private]
Definition at line 57 of file treescreen_old.h.
QAction* treescreen::action_del_branch [private]
Definition at line 58 of file treescreen_old.h.
The documentation for this class was generated from the following files:
treescreen.h
treescreen_old.h
treescreen.cpp