knowtreemodel Class Reference
#include <knowtreemodel.h>
Public Member Functions
knowtreemodel (const QStringList &headers, QDomDocument dommodel, QObject *parent=0)
~knowtreemodel ()
QDomElement export_fullmodeldata_to_dom (TreeItem *root)
void add_new_child_branch (const QModelIndex &index, QString id, QString name)
void add_new_sibling_branch (const QModelIndex &index, QString id, QString name)
void add_new_branch (TreeItem *parent, QString id, QString name)
QModelIndex move_up_branch (const QModelIndex &index)
QModelIndex move_dn_branch (const QModelIndex &index)
QModelIndex indexChildren (const QModelIndex &parent, int n) const
QModelIndex get_item_index (TreeItem *item)
Private Member Functions
void setupModelData (QDomDocument dommodel, TreeItem *parent)
void parsenodeelement (QDomElement n, TreeItem *parent)
void parsetreetodom (QDomElement *xmldata, TreeItem *curritem)
QModelIndex move_updn_branch (const QModelIndex &index, int direction)
QModelIndex get_item_index_recurse (QModelIndex currindex, TreeItem *finditem, int mode)
Detailed Description
Definition at line 12 of file knowtreemodel.h.
Constructor & Destructor Documentation
knowtreemodel::knowtreemodel (const QStringList & headers, QDomDocument dommodel, QObject * parent = 0)
Definition at line 13 of file knowtreemodel.cpp.
References TreeModel::rootItem, and setupModelData().
knowtreemodel::~knowtreemodel ()
Definition at line 33 of file knowtreemodel.cpp.
References TreeModel::rootItem.
Member Function Documentation
QDomElement knowtreemodel::export_fullmodeldata_to_dom (TreeItem * root)
Definition at line 99 of file knowtreemodel.cpp.
References parsetreetodom().
Referenced by treescreen::save_knowtree().
void knowtreemodel::add_new_child_branch (const QModelIndex & index, QString id, QString name)
Definition at line 175 of file knowtreemodel.cpp.
References add_new_branch(), TreeModel::getItem(), and TreeModel::parent().
Referenced by treescreen::ins_subbranch().
void knowtreemodel::add_new_sibling_branch (const QModelIndex & index, QString id, QString name)
Definition at line 187 of file knowtreemodel.cpp.
References add_new_branch(), TreeModel::getItem(), TreeItem::parent(), and TreeModel::parent().
Referenced by treescreen::ins_branch().
void knowtreemodel::add_new_branch (TreeItem * parent, QString id, QString name)
Definition at line 200 of file knowtreemodel.cpp.
References TreeModel::parent(), and TreeModel::setData().
Referenced by add_new_child_branch(), and add_new_sibling_branch().
QModelIndex knowtreemodel::move_up_branch (const QModelIndex & index)
Definition at line 215 of file knowtreemodel.cpp.
References move_updn_branch().
Referenced by treescreen::move_updn_branch().
QModelIndex knowtreemodel::move_dn_branch (const QModelIndex & index)
Definition at line 222 of file knowtreemodel.cpp.
References move_updn_branch().
Referenced by treescreen::move_updn_branch().
QModelIndex knowtreemodel::indexChildren (const QModelIndex & parent, int n) const
Definition at line 270 of file knowtreemodel.cpp.
References TreeItem::child(), TreeItem::childCount(), TreeModel::getItem(), and TreeModel::index().
Referenced by treescreen::ins_subbranch().
QModelIndex knowtreemodel::get_item_index (TreeItem * item)
Definition at line 311 of file knowtreemodel.cpp.
References TreeItem::childNumber().
Referenced by mainwindow::set_tree_position().
void knowtreemodel::setupModelData (QDomDocument dommodel, TreeItem * parent) [private]
Definition at line 40 of file knowtreemodel.cpp.
References TreeModel::parent(), and parsenodeelement().
Referenced by knowtreemodel().
void knowtreemodel::parsenodeelement (QDomElement n, TreeItem * parent) [private]
Definition at line 57 of file knowtreemodel.cpp.
References TreeItem::child(), TreeItem::childCount(), TreeItem::insertChildren(), TreeModel::parent(), TreeItem::recordtable_init(), and TreeModel::setData().
Referenced by setupModelData().
void knowtreemodel::parsetreetodom (QDomElement * xmldata, TreeItem * curritem) [private]
Definition at line 115 of file knowtreemodel.cpp.
References TreeItem::child(), TreeItem::childCount(), TreeItem::data(), TreeItem::recordtable_export_data_to_dom(), and TreeItem::recordtable_getrowcount().
Referenced by export_fullmodeldata_to_dom().
QModelIndex knowtreemodel::move_updn_branch (const QModelIndex & index, int direction) [private]
Definition at line 229 of file knowtreemodel.cpp.
References TreeModel::getItem(), TreeModel::index(), TreeItem::move_dn(), and TreeItem::move_up().
Referenced by move_dn_branch(), and move_up_branch().
QModelIndex knowtreemodel::get_item_index_recurse (QModelIndex currindex, TreeItem * finditem, int mode) [private]
The documentation for this class was generated from the following files:
knowtreemodel.h
knowtreemodel.cpp