PrintPreview Class Reference
#include <printpreview.h>
Public Member Functions
PrintPreview (const QTextDocument *document, QWidget *parent)
virtual ~PrintPreview ()
Private Slots
void print ()
void pageSetup ()
Private Member Functions
void setup ()
Private Attributes
QTextDocument * doc
PreviewView * view
QPrinter printer
Detailed Description
Definition at line 33 of file printpreview.h.
Constructor & Destructor Documentation
PrintPreview::PrintPreview (const QTextDocument * document, QWidget * parent)
Definition at line 206 of file printpreview.cpp.
References doc, inchesToPixels(), mmToInches(), pageSetup(), print(), printer, setup(), and view.
PrintPreview::~PrintPreview () [virtual]
Definition at line 282 of file printpreview.cpp.
References doc.
Member Function Documentation
void PrintPreview::print () [private, slot]
Definition at line 287 of file printpreview.cpp.
References doc, and printer.
Referenced by PrintPreview().
void PrintPreview::pageSetup () [private, slot]
Definition at line 296 of file printpreview.cpp.
References printer, setup(), PreviewView::updateLayout(), and view.
Referenced by PrintPreview().
void PrintPreview::setup () [private]
Definition at line 267 of file printpreview.cpp.
References doc, inchesToPixels(), mmToInches(), printer, and view.
Referenced by pageSetup(), and PrintPreview().
Member Data Documentation
QTextDocument* PrintPreview::doc [private]
Definition at line 47 of file printpreview.h.
Referenced by print(), PrintPreview(), setup(), and ~PrintPreview().
PreviewView* PrintPreview::view [private]
Definition at line 48 of file printpreview.h.
Referenced by pageSetup(), PrintPreview(), and setup().
QPrinter PrintPreview::printer [private]
Definition at line 49 of file printpreview.h.
Referenced by pageSetup(), print(), PrintPreview(), and setup().
The documentation for this class was generated from the following files:
printpreview.h
printpreview.cpp