findscreen Class Reference
#include <findscreen.h>
Public Slots
void widget_show (void)
void widget_hide (void)
Public Member Functions
findscreen (QWidget *parent=0)
virtual ~findscreen (void)
Private Slots
void enable_find_button (const QString &text)
void find_clicked (void)
void changed_wordregard (int pos)
void changed_howextract (int pos)
void changed_find_in_name (int state)
void changed_find_in_author (int state)
void changed_find_in_url (int state)
void changed_find_in_tags (int state)
void changed_find_in_text (int state)
Private Member Functions
void setup_toolsline (void)
void assembly_toolsline (void)
void setup_wherefindline (void)
void assembly_wherefindline (void)
void setup_ui (void)
void assembly (void)
void setup_signals (void)
void changed_find_in_field (QString fieldname, int state)
void find_start (void)
void find_recurse (TreeItem *curritem)
QStringList text_decompose (QString text)
bool find_in_text_process (const QString &text)
Private Attributes
QLineEdit * findtext
QPushButton * findstart
QComboBox * wordregard
QComboBox * howextract
QToolButton * closebutton
QLabel * wherefindlabel
QCheckBox * find_in_name
QCheckBox * find_in_author
QCheckBox * find_in_url
QCheckBox * find_in_tags
QCheckBox * find_in_text
QHBoxLayout * toolsline
QVBoxLayout * placeupclosebutton
QHBoxLayout * wherefindline
QVBoxLayout * centrallayout
findtablewidget * findtable
QMap< QString, bool > search_area
QStringList search_word_list
Detailed Description
Definition at line 21 of file findscreen.h.
Constructor & Destructor Documentation
findscreen::findscreen (QWidget * parent = 0)
Definition at line 21 of file findscreen.cpp.
References assembly(), assembly_toolsline(), assembly_wherefindline(), setup_signals(), setup_toolsline(), setup_ui(), and setup_wherefindline().
findscreen::~findscreen (void) [virtual]
Definition at line 36 of file findscreen.cpp.
Member Function Documentation
void findscreen::widget_show (void) [slot]
Definition at line 467 of file findscreen.cpp.
References mytetraconfig, and appconfig::set_findscreen_show().
Referenced by recordtablescreen::findinbase_open().
void findscreen::widget_hide (void) [slot]
Definition at line 474 of file findscreen.cpp.
References mytetraconfig, appconfig::set_findscreen_show(), and appconfig::set_findsplitter_size_list().
Referenced by recordtablescreen::findinbase_open(), and setup_signals().
void findscreen::enable_find_button (const QString & text) [private, slot]
Definition at line 197 of file findscreen.cpp.
References findstart.
Referenced by setup_signals().
void findscreen::find_clicked (void) [private, slot]
Definition at line 203 of file findscreen.cpp.
References find_in_author, find_in_name, find_in_tags, find_in_text, find_in_url, find_start(), findtext, search_area, search_word_list, and text_decompose().
Referenced by setup_signals().
void findscreen::changed_wordregard (int pos) [private, slot]
Definition at line 415 of file findscreen.cpp.
References mytetraconfig, and appconfig::set_findscreen_wordregard().
Referenced by setup_signals().
void findscreen::changed_howextract (int pos) [private, slot]
Definition at line 421 of file findscreen.cpp.
References mytetraconfig, and appconfig::set_findscreen_howextract().
Referenced by setup_signals().
void findscreen::changed_find_in_name (int state) [private, slot]
Definition at line 427 of file findscreen.cpp.
References changed_find_in_field().
Referenced by setup_signals().
void findscreen::changed_find_in_author (int state) [private, slot]
Definition at line 433 of file findscreen.cpp.
References changed_find_in_field().
Referenced by setup_signals().
void findscreen::changed_find_in_url (int state) [private, slot]
Definition at line 439 of file findscreen.cpp.
References changed_find_in_field().
Referenced by setup_signals().
void findscreen::changed_find_in_tags (int state) [private, slot]
Definition at line 445 of file findscreen.cpp.
References changed_find_in_field().
Referenced by setup_signals().
void findscreen::changed_find_in_text (int state) [private, slot]
Definition at line 451 of file findscreen.cpp.
References changed_find_in_field().
Referenced by setup_signals().
void findscreen::setup_toolsline (void) [private]
Definition at line 41 of file findscreen.cpp.
References closebutton, findstart, findtext, appconfig::get_findscreen_howextract(), appconfig::get_findscreen_wordregard(), howextract, imin(), mytetraconfig, and wordregard.
Referenced by findscreen().
void findscreen::assembly_toolsline (void) [private]
Definition at line 74 of file findscreen.cpp.
References closebutton, findstart, findtext, howextract, placeupclosebutton, toolsline, and wordregard.
Referenced by findscreen().
void findscreen::setup_wherefindline (void) [private]
Definition at line 97 of file findscreen.cpp.
References find_in_author, find_in_name, find_in_tags, find_in_text, find_in_url, appconfig::get_findscreen_find_in_field(), mytetraconfig, and wherefindlabel.
Referenced by findscreen().
void findscreen::assembly_wherefindline (void) [private]
Definition at line 118 of file findscreen.cpp.
References find_in_author, find_in_name, find_in_tags, find_in_text, find_in_url, wherefindlabel, and wherefindline.
Referenced by findscreen().
void findscreen::setup_ui (void) [private]
Definition at line 177 of file findscreen.cpp.
References findtable.
Referenced by findscreen().
void findscreen::assembly (void) [private]
Definition at line 184 of file findscreen.cpp.
References centrallayout, findtable, toolsline, and wherefindline.
Referenced by findscreen().
void findscreen::setup_signals (void) [private]
Definition at line 135 of file findscreen.cpp.
References changed_find_in_author(), changed_find_in_name(), changed_find_in_tags(), changed_find_in_text(), changed_find_in_url(), changed_howextract(), changed_wordregard(), closebutton, enable_find_button(), find_clicked(), find_in_author, find_in_name, find_in_tags, find_in_text, find_in_url, findstart, findtext, howextract, widget_hide(), and wordregard.
Referenced by findscreen().
void findscreen::changed_find_in_field (QString fieldname, int state) [private]
Definition at line 457 of file findscreen.cpp.
References mytetraconfig, and appconfig::set_findscreen_find_in_field().
Referenced by changed_find_in_author(), changed_find_in_name(), changed_find_in_tags(), changed_find_in_text(), and changed_find_in_url().
void findscreen::find_start (void) [private]
Definition at line 263 of file findscreen.cpp.
References findtablewidget::clear_all(), find_recurse(), findtable, TreeModel::rootItem, and findtablewidget::update_columns_width().
Referenced by find_clicked().
void findscreen::find_recurse (TreeItem * curritem) [private]
Definition at line 279 of file findscreen.cpp.
References findtablewidget::add_row(), TreeItem::child(), TreeItem::childCount(), TreeItem::data(), find_in_text_process(), findtable, TreeItem::get_path(), TreeItem::recordtable_getrowcount(), TreeItem::recordtable_gettabledata(), and search_area.
Referenced by find_start().
QStringList findscreen::text_decompose (QString text) [private]
Definition at line 245 of file findscreen.cpp.
Referenced by find_clicked(), and find_in_text_process().
bool findscreen::find_in_text_process (const QString & text) [private]
Definition at line 368 of file findscreen.cpp.
References howextract, search_word_list, text_decompose(), and wordregard.
Referenced by find_recurse().
Member Data Documentation
QLineEdit* findscreen::findtext [private]
Definition at line 47 of file findscreen.h.
Referenced by assembly_toolsline(), find_clicked(), setup_signals(), and setup_toolsline().
QPushButton* findscreen::findstart [private]
Definition at line 48 of file findscreen.h.
Referenced by assembly_toolsline(), enable_find_button(), setup_signals(), and setup_toolsline().
QComboBox* findscreen::wordregard [private]
Definition at line 49 of file findscreen.h.
Referenced by assembly_toolsline(), find_in_text_process(), setup_signals(), and setup_toolsline().
QComboBox* findscreen::howextract [private]
Definition at line 50 of file findscreen.h.
Referenced by assembly_toolsline(), find_in_text_process(), setup_signals(), and setup_toolsline().
QToolButton* findscreen::closebutton [private]
Definition at line 51 of file findscreen.h.
Referenced by assembly_toolsline(), setup_signals(), and setup_toolsline().
QLabel* findscreen::wherefindlabel [private]
Definition at line 53 of file findscreen.h.
Referenced by assembly_wherefindline(), and setup_wherefindline().
QCheckBox* findscreen::find_in_name [private]
Definition at line 54 of file findscreen.h.
Referenced by assembly_wherefindline(), find_clicked(), setup_signals(), and setup_wherefindline().
QCheckBox* findscreen::find_in_author [private]
Definition at line 55 of file findscreen.h.
Referenced by assembly_wherefindline(), find_clicked(), setup_signals(), and setup_wherefindline().
QCheckBox* findscreen::find_in_url [private]
Definition at line 56 of file findscreen.h.
Referenced by assembly_wherefindline(), find_clicked(), setup_signals(), and setup_wherefindline().
QCheckBox* findscreen::find_in_tags [private]
Definition at line 57 of file findscreen.h.
Referenced by assembly_wherefindline(), find_clicked(), setup_signals(), and setup_wherefindline().
QCheckBox* findscreen::find_in_text [private]
Definition at line 58 of file findscreen.h.
Referenced by assembly_wherefindline(), find_clicked(), setup_signals(), and setup_wherefindline().
QHBoxLayout* findscreen::toolsline [private]
Definition at line 60 of file findscreen.h.
Referenced by assembly(), and assembly_toolsline().
QVBoxLayout* findscreen::placeupclosebutton [private]
Definition at line 61 of file findscreen.h.
Referenced by assembly_toolsline().
QHBoxLayout* findscreen::wherefindline [private]
Definition at line 62 of file findscreen.h.
Referenced by assembly(), and assembly_wherefindline().
QVBoxLayout* findscreen::centrallayout [private]
Definition at line 63 of file findscreen.h.
Referenced by assembly().
findtablewidget* findscreen::findtable [private]
Definition at line 65 of file findscreen.h.
Referenced by assembly(), find_recurse(), find_start(), and setup_ui().
QMap<QString, bool> findscreen::search_area [private]
Definition at line 86 of file findscreen.h.
Referenced by find_clicked(), and find_recurse().
QStringList findscreen::search_word_list [private]
Definition at line 89 of file findscreen.h.
Referenced by find_clicked(), and find_in_text_process().
The documentation for this class was generated from the following files:
findscreen.h
findscreen.cpp