appconfig Class Reference
#include <appconfig.h>
Public Member Functions
appconfig (QObject *pobj=0)
~appconfig ()
QString get_tetradir (void)
bool set_tetradir (QString dirname)
QString get_trashdir (void)
bool set_trashdir (QString dirname)
int get_lastnotenum (void)
QString get_lastnotenum_as_line (void)
void inc_lastnotenum (void)
int get_lastidnum (void)
void inc_lastidnum (void)
int get_lastprefixnum (void)
QString get_lastprefixnum_as_line (void)
void inc_lastprefixnum (void)
QString get_addnewrecord_expand_info (void)
void set_addnewrecord_expand_info (QString)
QRect get_mainwingeometry (void)
void set_mainwingeometry (int x, int y, int w, int h)
QList< int > get_vspl_size_list (void)
void set_vspl_size_list (QList< int > list)
QList< int > get_hspl_size_list (void)
void set_hspl_size_list (QList< int > list)
QList< int > get_findsplitter_size_list (void)
void set_findsplitter_size_list (QList< int > list)
QList< int > get_splitter_size_list (QString name)
void set_splitter_size_list (QString name, QList< int > list)
QStringList get_tree_position (void)
void set_tree_position (QStringList list)
int get_recordtable_position (void)
void set_recordtable_position (int pos)
int get_findscreen_wordregard (void)
void set_findscreen_wordregard (int pos)
int get_findscreen_howextract (void)
void set_findscreen_howextract (int pos)
bool get_findscreen_find_in_field (QString fieldname)
void set_findscreen_find_in_field (QString fieldname, bool ischecked)
bool get_findscreen_show (void)
void set_findscreen_show (bool isshow)
Private Member Functions
QString get_parameter (QString)
Static Private Attributes
static QSettings conf
Detailed Description
Definition at line 12 of file appconfig.h.
Constructor & Destructor Documentation
appconfig::appconfig (QObject * pobj = 0)
Definition at line 12 of file appconfig.cpp.
References conf, and critical_error().
appconfig::~appconfig ()
Definition at line 27 of file appconfig.cpp.
Member Function Documentation
QString appconfig::get_tetradir (void)
Definition at line 62 of file appconfig.cpp.
References get_parameter().
Referenced by recordtabledata::delete_record(), recordtablescreen::get_fullfilename_of_currentitem(), recordtabledata::get_text(), treescreen::init_knowtree(), recordtabledata::insert_new_record(), treescreen::save_knowtree(), and recordtablescreen::select().
bool appconfig::set_tetradir (QString dirname)
Definition at line 47 of file appconfig.cpp.
References conf.
QString appconfig::get_trashdir (void)
Definition at line 84 of file appconfig.cpp.
References get_parameter().
Referenced by remove_dir(), mainwindow::save_current_record_text(), and treescreen::save_knowtree().
bool appconfig::set_trashdir (QString dirname)
Definition at line 69 of file appconfig.cpp.
References conf.
int appconfig::get_lastnotenum (void)
Definition at line 91 of file appconfig.cpp.
References get_parameter().
Referenced by inc_lastnotenum().
QString appconfig::get_lastnotenum_as_line (void)
Definition at line 103 of file appconfig.cpp.
References get_parameter().
Referenced by recordtabledata::insert_new_record().
void appconfig::inc_lastnotenum (void)
Definition at line 114 of file appconfig.cpp.
References conf, and get_lastnotenum().
Referenced by recordtabledata::insert_new_record().
int appconfig::get_lastidnum (void)
Definition at line 126 of file appconfig.cpp.
References get_parameter().
Referenced by inc_lastidnum(), treescreen::ins_branch(), treescreen::ins_subbranch(), and recordtabledata::insert_new_record().
void appconfig::inc_lastidnum (void)
Definition at line 138 of file appconfig.cpp.
References conf, and get_lastidnum().
Referenced by treescreen::ins_branch(), treescreen::ins_subbranch(), and recordtabledata::insert_new_record().
int appconfig::get_lastprefixnum (void)
Definition at line 150 of file appconfig.cpp.
References get_parameter().
Referenced by inc_lastprefixnum().
QString appconfig::get_lastprefixnum_as_line (void)
Definition at line 162 of file appconfig.cpp.
References get_parameter().
Referenced by remove_dir(), mainwindow::save_current_record_text(), and treescreen::save_knowtree().
void appconfig::inc_lastprefixnum (void)
Definition at line 173 of file appconfig.cpp.
References conf, and get_lastprefixnum().
Referenced by remove_dir(), mainwindow::save_current_record_text(), and treescreen::save_knowtree().
QString appconfig::get_addnewrecord_expand_info (void)
Definition at line 183 of file appconfig.cpp.
References get_parameter().
Referenced by infofieldenter::assembly(), infofieldenter::expand_info_click(), and infofieldenter::setup_ui().
void appconfig::set_addnewrecord_expand_info (QString)
Definition at line 188 of file appconfig.cpp.
References conf, and critical_error().
Referenced by infofieldenter::expand_info_click().
QRect appconfig::get_mainwingeometry (void)
Definition at line 197 of file appconfig.cpp.
References conf.
Referenced by mainwindow::restore_geometry().
void appconfig::set_mainwingeometry (int x, int y, int w, int h)
Definition at line 203 of file appconfig.cpp.
References conf.
Referenced by mainwindow::save_geometry().
QList< int > appconfig::get_vspl_size_list (void)
Definition at line 210 of file appconfig.cpp.
References get_splitter_size_list().
Referenced by mainwindow::restore_geometry().
void appconfig::set_vspl_size_list (QList< int > list)
Definition at line 216 of file appconfig.cpp.
References set_splitter_size_list().
Referenced by mainwindow::save_geometry().
QList< int > appconfig::get_hspl_size_list (void)
Definition at line 222 of file appconfig.cpp.
References get_splitter_size_list().
Referenced by mainwindow::restore_geometry().
void appconfig::set_hspl_size_list (QList< int > list)
Definition at line 228 of file appconfig.cpp.
References set_splitter_size_list().
Referenced by mainwindow::save_geometry().
QList< int > appconfig::get_findsplitter_size_list (void)
Definition at line 234 of file appconfig.cpp.
References get_splitter_size_list().
Referenced by mainwindow::restore_geometry().
void appconfig::set_findsplitter_size_list (QList< int > list)
Definition at line 240 of file appconfig.cpp.
References set_splitter_size_list().
Referenced by mainwindow::save_geometry(), and findscreen::widget_hide().
QList< int > appconfig::get_splitter_size_list (QString name)
Definition at line 246 of file appconfig.cpp.
References conf.
Referenced by get_findsplitter_size_list(), get_hspl_size_list(), and get_vspl_size_list().
void appconfig::set_splitter_size_list (QString name, QList< int > list)
Definition at line 260 of file appconfig.cpp.
References conf.
Referenced by set_findsplitter_size_list(), set_hspl_size_list(), and set_vspl_size_list().
QStringList appconfig::get_tree_position (void)
Definition at line 271 of file appconfig.cpp.
References conf.
Referenced by mainwindow::restore_tree_position().
void appconfig::set_tree_position (QStringList list)
Definition at line 277 of file appconfig.cpp.
References conf.
Referenced by mainwindow::save_tree_position().
int appconfig::get_recordtable_position (void)
Definition at line 283 of file appconfig.cpp.
References conf.
Referenced by mainwindow::restore_recordtable_position().
void appconfig::set_recordtable_position (int pos)
Definition at line 289 of file appconfig.cpp.
References conf.
Referenced by mainwindow::save_recordtable_position().
int appconfig::get_findscreen_wordregard (void)
Definition at line 295 of file appconfig.cpp.
References conf.
Referenced by findscreen::setup_toolsline().
void appconfig::set_findscreen_wordregard (int pos)
Definition at line 301 of file appconfig.cpp.
References conf.
Referenced by findscreen::changed_wordregard().
int appconfig::get_findscreen_howextract (void)
Definition at line 307 of file appconfig.cpp.
References conf.
Referenced by findscreen::setup_toolsline().
void appconfig::set_findscreen_howextract (int pos)
Definition at line 313 of file appconfig.cpp.
References conf.
Referenced by findscreen::changed_howextract().
bool appconfig::get_findscreen_find_in_field (QString fieldname)
Definition at line 319 of file appconfig.cpp.
References conf.
Referenced by findscreen::setup_wherefindline().
void appconfig::set_findscreen_find_in_field (QString fieldname, bool ischecked)
Definition at line 325 of file appconfig.cpp.
References conf.
Referenced by findscreen::changed_find_in_field().
bool appconfig::get_findscreen_show (void)
Definition at line 331 of file appconfig.cpp.
References conf.
Referenced by mainwindow::restore_findonbase_visible().
void appconfig::set_findscreen_show (bool isshow)
Definition at line 337 of file appconfig.cpp.
References conf.
Referenced by findscreen::widget_hide(), and findscreen::widget_show().
QString appconfig::get_parameter (QString) [private]
Definition at line 34 of file appconfig.cpp.
References conf, and critical_error().
Referenced by get_addnewrecord_expand_info(), get_lastidnum(), get_lastnotenum(), get_lastnotenum_as_line(), get_lastprefixnum(), get_lastprefixnum_as_line(), get_tetradir(), and get_trashdir().
Member Data Documentation
QSettings appconfig::conf [static, private]
Definition at line 84 of file appconfig.h.
Referenced by appconfig(), get_findscreen_find_in_field(), get_findscreen_howextract(), get_findscreen_show(), get_findscreen_wordregard(), get_mainwingeometry(), get_parameter(), get_recordtable_position(), get_splitter_size_list(), get_tree_position(), inc_lastidnum(), inc_lastnotenum(), inc_lastprefixnum(), set_addnewrecord_expand_info(), set_findscreen_find_in_field(), set_findscreen_howextract(), set_findscreen_show(), set_findscreen_wordregard(), set_mainwingeometry(), set_recordtable_position(), set_splitter_size_list(), set_tetradir(), set_trashdir(), and set_tree_position().
The documentation for this class was generated from the following files:
appconfig.h
appconfig.cpp