printpreview.cpp File Reference
#include <QAbstractScrollArea>
#include <QPrintDialog>
#include <QPrinter>
#include <QToolBar>
#include <QAction>
#include <QTextFormat>
#include <QMouseEvent>
#include <QTextFrame>
#include <QTextDocument>
#include <QAbstractTextDocumentLayout>
#include <QScrollBar>
#include <QPainter>
#include <QDebug>
#include <QPageSetupDialog>
#include <QStatusBar>
#include `printpreview.h`
#include `printpreview.moc`
Classes
class PreviewView
Functions
static int inchesToPixels (float inches, QPaintDevice *device)
static qreal mmToInches (double mm)
Variables
const QString rsrcPath = `:/images/win`
Function Documentation
static int inchesToPixels (float inches, QPaintDevice * device) [inline, static]
Definition at line 48 of file printpreview.cpp.
Referenced by PrintPreview::PrintPreview(), and PrintPreview::setup().
static qreal mmToInches (double mm) [inline, static]
Definition at line 53 of file printpreview.cpp.
Referenced by PrintPreview::PrintPreview(), and PrintPreview::setup().
Variable Documentation
const QString rsrcPath = `:/images/win`
Definition at line 45 of file printpreview.cpp.